In [2]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census

In [8]:
csv_file = '../green_city/medianHouseholdIncome.csv'
csv_file

'../green_city/medianHouseholdIncome.csv'

In [9]:
Household_Income_df = pd.read_csv(csv_file)
Household_Income_df

,Year,State,County ID,State / County Name,All Ages SAIPE Poverty Universe,All Ages in Poverty Count,All Ages in Poverty Count LB 90%,All Ages in Poverty Count UB 90%,90% Confidence Interval (All Ages in Poverty Count),All Ages in Poverty Percent,...,Under Age 5 in Poverty Count UB 90%,90% Confidence Interval (Under Age 5 in Poverty Count),Under Age 5 in Poverty Percent,Under Age 5 in Poverty Percent LB 90%,Under Age 5 in Poverty Percent UB 90%,90% Confidence Interval (Under Age 5 in Poverty Percent),Median Household Income in Dollars,Median Household Income in Dollars LB 90%,Median Household Income in Dollars UB 90%,90% Confidence Interval (Median Household Income in Dollars)
0,2015,45,45001,Abbeville County (SC),"24,140","4,617","3,725","5,509","3,725 to 5,509",19.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$35,932","$32,690","$39,174","$32,690 to $39,174"
1,2014,45,45001,Abbeville County (SC),"24,184","5,178","4,309","6,047","4,309 to 6,047",21.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$35,525","$32,040","$39,010","$32,040 to $39,010"
2,2013,45,45001,Abbeville County (SC),"24,241","4,918","3,987","5,849","3,987 to 5,849",20.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$36,187","$32,906","$39,468","$32,906 to $39,468"
3,2012,45,45001,Abbeville County (SC),"24,359","4,911","4,017","5,805","4,017 to 5,805",20.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$35,456","$32,612","$38,300","$32,612 to $38,300"
4,2011,45,45001,Abbeville County (SC),"24,406","4,986","4,084","5,888","4,084 to 5,888",20.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$36,787","$34,111","$39,463","$34,111 to $39,463"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19163,2014,46,46137,Ziebach County (SD),"2,821","1,257",987,"1,527","987 to 1,527",44.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$32,025","$29,359","$34,691","$29,359 to $34,691"
19164,2013,46,46137,Ziebach County (SD),"2,824","1,376","1,118","1,634","1,118 to 1,634",48.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$30,465","$27,332","$33,598","$27,332 to $33,598"
19165,2012,46,46137,Ziebach County (SD),"2,863","1,335","1,056","1,614","1,056 to 1,614",46.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$30,856","$28,308","$33,404","$28,308 to $33,404"
19166,2011,46,46137,Ziebach County (SD),"2,846","1,419","1,118","1,720","1,118 to 1,720",49.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$28,350","$25,347","$31,353","$25,347 to $31,353"
19167,2010,46,46137,Ziebach County (SD),"2,816","1,410","1,114","1,706","1,114 to 1,706",50.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$25,669","$23,137","$28,201","$23,137 to $28,201"

In [10]:
Household_Income_df["State / County Name"].value_counts()

Chittenden County (VT)         6
Hampton city (VA)              6
Early County (GA)              6
Benton County (TN)             6
Beaufort County (SC)           6
                              ..
Bedford city (VA)              4
Petersburg Census Area (AK)    4
Petersburg Borough (AK)        2
Oglala Lakota County (SD)      1
Kusilvak Census Area (AK)      1
Name: State / County Name, Length: 3198, dtype: int64

# Sanfrancisco, CA

In [12]:
CA_Household_Income_df = Household_Income_df.loc[(Household_Income_df["State"]==6)]
CA_Household_Income_df.head(50)

,Year,State,County ID,State / County Name,All Ages SAIPE Poverty Universe,All Ages in Poverty Count,All Ages in Poverty Count LB 90%,All Ages in Poverty Count UB 90%,90% Confidence Interval (All Ages in Poverty Count),All Ages in Poverty Percent,...,Under Age 5 in Poverty Count UB 90%,90% Confidence Interval (Under Age 5 in Poverty Count),Under Age 5 in Poverty Percent,Under Age 5 in Poverty Percent LB 90%,Under Age 5 in Poverty Percent UB 90%,90% Confidence Interval (Under Age 5 in Poverty Percent),Median Household Income in Dollars,Median Household Income in Dollars LB 90%,Median Household Income in Dollars UB 90%,90% Confidence Interval (Median Household Income in Dollars)
156,2015,6,6001,Alameda County (CA),"1,609,162","184,716","172,690","196,742","172,690 to 196,742",11.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$81,462","$80,249","$82,675","$80,249 to $82,675"
157,2014,6,6001,Alameda County (CA),"1,581,548","197,984","186,953","209,015","186,953 to 209,015",12.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$76,996","$75,788","$78,204","$75,788 to $78,204"
158,2013,6,6001,Alameda County (CA),"1,549,789","201,303","189,228","213,378","189,228 to 213,378",13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$72,128","$70,566","$73,690","$70,566 to $73,690"
159,2012,6,6001,Alameda County (CA),"1,526,032","200,101","189,366","210,836","189,366 to 210,836",13.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$70,209","$68,893","$71,525","$68,893 to $71,525"
160,2011,6,6001,Alameda County (CA),"1,500,076","198,382","185,035","211,729","185,035 to 211,729",13.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$67,295","$65,680","$68,910","$65,680 to $68,910"
161,2010,6,6001,Alameda County (CA),"1,483,946","200,273","185,384","215,162","185,384 to 215,162",13.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$66,937","$65,510","$68,364","$65,510 to $68,364"
330,2015,6,6003,Alpine County (CA),"1,107",210,163,257,163 to 257,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$50,882","$45,513","$56,251","$45,513 to $56,251"
331,2014,6,6003,Alpine County (CA),"1,112",211,164,258,164 to 258,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$53,003","$48,227","$57,779","$48,227 to $57,779"
332,2013,6,6003,Alpine County (CA),"1,155",227,178,276,178 to 276,19.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$49,392","$44,466","$54,318","$44,466 to $54,318"
333,2012,6,6003,Alpine County (CA),"1,125",217,174,260,174 to 260,19.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$46,336","$41,770","$50,902","$41,770 to $50,902"
334,2011,6,6003,Alpine County (CA),"1,098",191,146,236,146 to 236,17.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$46,706","$42,096","$51,316","$42,096 to $51,316"
335,2010,6,6003,Alpine County (CA),"1,158",196,150,242,150 to 242,16.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$44,241","$39,968","$48,514","$39,968 to $48,514"
336,2015,6,6005,Amador County (CA),"33,746","4,404","3,592","5,216","3,592 to 5,216",13.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$55,879","$51,082","$60,676","$51,082 to $60,676"
337,2014,6,6005,Amador County (CA),"33,486","4,313","3,381","5,245","3,381 to 5,245",12.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$54,610","$49,602","$59,618","$49,602 to $59,618"
338,2013,6,6005,Amador County (CA),"33,247","4,746","3,876","5,616","3,876 to 5,616",14.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$52,357","$47,826","$56,888","$47,826 to $56,888"
339,2012,6,6005,Amador County (CA),"33,229","4,425","3,607","5,243","3,607 to 5,243",13.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$51,388","$46,902","$55,874","$46,902 to $55,874"
340,2011,6,6005,Amador County (CA),"33,428","4,670","3,796","5,544","3,796 to 5,544",14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$51,553","$46,598","$56,508","$46,598 to $56,508"
341,2010,6,6005,Amador County (CA),"33,512","4,286","3,409","5,163","3,409 to 5,163",12.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$49,516","$45,821","$53,211","$45,821 to $53,211"
2008,2015,6,6007,Butte County (CA),"220,672","47,269","43,235","51,303","43,235 to 51,303",21.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$45,369","$43,693","$47,045","$43,693 to $47,045"
2009,2014,6,6007,Butte County (CA),"219,602","48,151","44,057","52,245","44,057 to 52,245",21.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$42,302","$40,264","$44,340","$40,264 to $44,340"
2010,2013,6,6007,Butte County (CA),"217,405","46,621","42,225","51,017","42,225 to 51,017",21.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$42,395","$40,338","$44,452","$40,338 to $44,452"
2011,2012,6,6007,Butte County (CA),"216,944","47,341","42,954","51,728","42,954 to 51,728",21.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$40,748","$38,995","$42,501","$38,995 to $42,501"
2012,2011,6,6007,Butte County (CA),"216,002","48,784","43,958","53,610","43,958 to 53,610",22.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$39,208","$37,490","$40,926","$37,490 to $40,926"
2013,2010,6,6007,Butte County (CA),"215,767","43,392","38,600","48,184","38,600 to 48,184",20.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$41,168","$39,227","$43,109","$39,227 to $43,109"
2062,2015,6,6009,Calaveras County (CA),"44,306","5,781","4,598","6,964","4,598 to 6,964",13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$52,471","$47,918","$57,024","$47,918 to $57,024"
2063,2014,6,6009,Calaveras County (CA),"44,098","6,057","4,889","7,225","4,889 to 7,225",13.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$53,321","$48,734","$57,908","$48,734 to $57,908"
2064,2013,6,6009,Calaveras County (CA),"43,979","6,617","5,453","7,781","5,453 to 7,781",15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$52,598","$48,423","$56,773","$48,423 to $56,773"
2065,2012,6,6009,Calaveras County (CA),"44,225","6,249","5,090","7,408","5,090 to 7,408",14.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$50,962","$46,767","$55,157","$46,767 to $55,157"
2066,2011,6,6009,Calaveras County (CA),"44,514","5,563","4,355","6,771","4,355 to 6,771",12.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$50,599","$45,986","$55,212","$45,986 to $55,212"
2067,2010,6,6009,Calaveras County (CA),"44,942","4,996","3,771","6,221","3,771 to 6,221",11.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$50,745","$47,183","$54,307","$47,183 to $54,307"
2176,2015,6,6000,California,"38,398,077","5,896,255","5,844,717","5,947,793","5,844,717 to 5,947,793",15.4,...,"559,761","535,757 to 559,761",22.3,21.8,22.8,21.8 to 22.8,"$64,483","$64,091","$64,875","$64,091 to $64,875"
2177,2014,6,6000,California,"38,060,226","6,253,423","6,203,456","6,303,390","6,203,456 to 6,303,390",16.4,...,"589,460","562,058 to 589,460",23.4,22.8,24.0,22.8 to 24.0,"$61,927","$61,689","$62,165","$61,689 to $62,165"
2178,2013,6,6000,California,"37,593,095","6,328,064","6,276,939","6,379,189","6,276,939 to 6,379,189",16.8,...,"621,315","594,445 to 621,315",24.8,24.3,25.3,24.3 to 25.3,"$60,185","$59,931","$60,439","$59,931 to $60,439"
2179,2012,6,6000,California,"37,303,312","6,323,433","6,274,914","6,371,952","6,274,914 to 6,371,952",17.0,...,"639,006","612,806 to 639,006",25.1,24.6,25.6,24.6 to 25.6,"$58,322","$57,972","$58,672","$57,972 to $58,672"
2180,2011,6,6000,California,"36,941,941","6,121,726","6,065,691","6,177,761","6,065,691 to 6,177,761",16.6,...,"628,501","601,173 to 628,501",24.7,24.2,25.2,24.2 to 25.2,"$57,275","$56,997","$57,553","$56,997 to $57,553"
2181,2010,6,6000,California,"36,593,422","5,785,036","5,732,381","5,837,691","5,732,381 to 5,837,691",15.8,...,"602,441","573,739 to 602,441",23.7,23.1,24.3,23.1 to 24.3,"$57,664","$57,316","$58,012","$57,316 to $58,012"
3730,2015,6,6011,Colusa County (CA),"21,231","2,800","2,250","3,350","2,250 to 3,350",13.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$51,118","$46,535","$55,701","$46,535 to $55,701"
3731,2014,6,6011,Colusa County (CA),"21,170","3,030","2,458","3,602","2,458 to 3,602",14.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$48,006","$44,053","$51,959","$44,053 to $51,959"
3732,2013,6,6011,Colusa County (CA),"21,117","2,749","2,155","3,343","2,155 to 3,343",13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$48,897","$44,917","$52,877","$44,917 to $52,877"
3733,2012,6,6011,Colusa County (CA),"21,176","2,835","2,279","3,391","2,279 to 3,391",13.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$49,871","$45,865","$53,877","$45,865 to $53,877"
3734,2011,6,6011,Colusa County (CA),"21,330","2,825","2,259","3,391","2,259 to 3,391",13.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$47,469","$43,205","$51,733","$43,205 to $51,733"
3735,2010,6,6011,Colusa County (CA),"21,250","3,161","2,528","3,794","2,528 to 3,794",14.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$44,981","$41,129","$48,833","$41,129 to $48,833"
3790,2015,6,6013,Contra Costa County (CA),"1,117,234","114,123","105,419","122,827","105,419 to 122,827",10.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$83,036","$80,380","$85,692","$80,380 to $85,692"
3791,2014,6,6013,Contra Costa County (CA),"1,102,107","115,466","106,262","124,670","106,262 to 124,670",10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$80,338","$78,400","$82,276","$78,400 to $82,276"
3792,2013,6,6013,Contra Costa County (CA),"1,084,752","116,977","108,232","125,722","108,232 to 125,722",10.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$78,909","$76,035","$81,783","$76,035 to $81,783"
3793,2012,6,6013,Contra Costa County (CA),"1,070,407","118,696","109,674","127,718","109,674 to 127,718",11.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$74,208","$72,512","$75,904","$72,512 to $75,904"
3794,2011,6,6013,Contra Costa County (CA),"1,056,995","125,467","116,362","134,572","116,362 to 134,572",11.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$74,241","$71,679","$76,803","$71,679 to $76,803"
3795,2010,6,6013,Contra Costa County (CA),"1,043,545","97,544","88,059","107,029","88,059 to 107,029",9.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$73,678","$71,878","$75,478","$71,878 to $75,478"
4564,2015,6,6015,Del Norte County (CA),"24,158","5,639","4,543","6,735","4,543 to 6,735",23.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$38,963","$35,115","$42,811","$35,115 to $42,811"
4565,2014,6,6015,Del Norte County (CA),"24,089","5,388","4,271","6,505","4,271 to 6,505",22.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$41,419","$38,181","$44,657","$38,181 to $44,657"

In [18]:
CA_Household_Income_df["State / County Name"].value_counts(ascending=False)

Madera County (CA)             6
Del Norte County (CA)          6
San Bernardino County (CA)     6
Santa Cruz County (CA)         6
Alameda County (CA)            6
Colusa County (CA)             6
Glenn County (CA)              6
Solano County (CA)             6
Placer County (CA)             6
Modoc County (CA)              6
Imperial County (CA)           6
San Mateo County (CA)          6
Riverside County (CA)          6
San Luis Obispo County (CA)    6
Tehama County (CA)             6
Ventura County (CA)            6
Stanislaus County (CA)         6
Orange County (CA)             6
Sonoma County (CA)             6
Tulare County (CA)             6
Mariposa County (CA)           6
Humboldt County (CA)           6
Santa Clara County (CA)        6
Yuba County (CA)               6
Trinity County (CA)            6
Inyo County (CA)               6
Sutter County (CA)             6
California                     6
Lake County (CA)               6
Los Angeles County (CA)        6
Mendocino County (CA)          6
Monterey County (CA)           6
Siskiyou County (CA)           6
Merced County (CA)             6
Shasta County (CA)             6
Napa County (CA)               6
Mono County (CA)               6
Amador County (CA)             6
Nevada County (CA)             6
Kern County (CA)               6
Santa Barbara County (CA)      6
Plumas County (CA)             6
Tuolumne County (CA)           6
Sierra County (CA)             6
Butte County (CA)              6
San Benito County (CA)         6
Calaveras County (CA)          6
Sacramento County (CA)         6
Lassen County (CA)             6
Kings County (CA)              6
Fresno County (CA)             6
Contra Costa County (CA)       6
El Dorado County (CA)          6
Yolo County (CA)               6
Marin County (CA)              6
San Diego County (CA)          6
Alpine County (CA)             6
San Joaquin County (CA)        6
San Francisco County (CA)      6
Name: State / County Name, dtype: int64

In [20]:
SF_CA_Income_df = CA_Household_Income_df.loc[(CA_Household_Income_df["State / County Name"]=="Alameda County (CA)") | (CA_Household_Income_df["State / County Name"]=="Contra Costa County (CA)") | (CA_Household_Income_df["State / County Name"]=="Marin County (CA)") | (CA_Household_Income_df["State / County Name"]=="Napa County (CA)") | (CA_Household_Income_df["State / County Name"]=="San Francisco County (CA)") | (CA_Household_Income_df["State / County Name"]=="San Mateo County (CA)") | (CA_Household_Income_df["State / County Name"]=="Santa Clara County (CA)") | (CA_Household_Income_df["State / County Name"]=="Solano County (CA)") | (CA_Household_Income_df["State / County Name"]=="Sonoma County (CA)") | (CA_Household_Income_df["State / County Name"]=="Solano County, CA") | (CA_Household_Income_df["State / County Name"]=="Sonoma County, CA")]
SF_CA_Income_df

,Year,State,County ID,State / County Name,All Ages SAIPE Poverty Universe,All Ages in Poverty Count,All Ages in Poverty Count LB 90%,All Ages in Poverty Count UB 90%,90% Confidence Interval (All Ages in Poverty Count),All Ages in Poverty Percent,...,Under Age 5 in Poverty Count UB 90%,90% Confidence Interval (Under Age 5 in Poverty Count),Under Age 5 in Poverty Percent,Under Age 5 in Poverty Percent LB 90%,Under Age 5 in Poverty Percent UB 90%,90% Confidence Interval (Under Age 5 in Poverty Percent),Median Household Income in Dollars,Median Household Income in Dollars LB 90%,Median Household Income in Dollars UB 90%,90% Confidence Interval (Median Household Income in Dollars)
156,2015,6,6001,Alameda County (CA),"1,609,162","184,716","172,690","196,742","172,690 to 196,742",11.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$81,462","$80,249","$82,675","$80,249 to $82,675"
157,2014,6,6001,Alameda County (CA),"1,581,548","197,984","186,953","209,015","186,953 to 209,015",12.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$76,996","$75,788","$78,204","$75,788 to $78,204"
158,2013,6,6001,Alameda County (CA),"1,549,789","201,303","189,228","213,378","189,228 to 213,378",13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$72,128","$70,566","$73,690","$70,566 to $73,690"
159,2012,6,6001,Alameda County (CA),"1,526,032","200,101","189,366","210,836","189,366 to 210,836",13.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$70,209","$68,893","$71,525","$68,893 to $71,525"
160,2011,6,6001,Alameda County (CA),"1,500,076","198,382","185,035","211,729","185,035 to 211,729",13.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$67,295","$65,680","$68,910","$65,680 to $68,910"
161,2010,6,6001,Alameda County (CA),"1,483,946","200,273","185,384","215,162","185,384 to 215,162",13.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$66,937","$65,510","$68,364","$65,510 to $68,364"
3790,2015,6,6013,Contra Costa County (CA),"1,117,234","114,123","105,419","122,827","105,419 to 122,827",10.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$83,036","$80,380","$85,692","$80,380 to $85,692"
3791,2014,6,6013,Contra Costa County (CA),"1,102,107","115,466","106,262","124,670","106,262 to 124,670",10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$80,338","$78,400","$82,276","$78,400 to $82,276"
3792,2013,6,6013,Contra Costa County (CA),"1,084,752","116,977","108,232","125,722","108,232 to 125,722",10.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$78,909","$76,035","$81,783","$76,035 to $81,783"
3793,2012,6,6013,Contra Costa County (CA),"1,070,407","118,696","109,674","127,718","109,674 to 127,718",11.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$74,208","$72,512","$75,904","$72,512 to $75,904"
3794,2011,6,6013,Contra Costa County (CA),"1,056,995","125,467","116,362","134,572","116,362 to 134,572",11.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$74,241","$71,679","$76,803","$71,679 to $76,803"
3795,2010,6,6013,Contra Costa County (CA),"1,043,545","97,544","88,059","107,029","88,059 to 107,029",9.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$73,678","$71,878","$75,478","$71,878 to $75,478"
10835,2015,6,6041,Marin County (CA),"254,348","19,100","16,297","21,903","16,297 to 21,903",7.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$99,868","$95,541","$104,195","$95,541 to $104,195"
10836,2014,6,6041,Marin County (CA),"253,902","22,272","19,261","25,283","19,261 to 25,283",8.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$94,549","$88,283","$100,815","$88,283 to $100,815"
10837,2013,6,6041,Marin County (CA),"251,556","21,784","18,694","24,874","18,694 to 24,874",8.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$94,347","$89,659","$99,035","$89,659 to $99,035"
10838,2012,6,6041,Marin County (CA),"249,013","21,058","17,892","24,224","17,892 to 24,224",8.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$88,654","$84,146","$93,162","$84,146 to $93,162"
10839,2011,6,6041,Marin County (CA),"247,458","23,236","19,887","26,585","19,887 to 26,585",9.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$78,470","$74,282","$82,658","$74,282 to $82,658"
10840,2010,6,6041,Marin County (CA),"245,311","22,456","18,863","26,049","18,863 to 26,049",9.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$82,383","$77,154","$87,612","$77,154 to $87,612"
12395,2015,6,6055,Napa County (CA),"138,096","13,960","11,953","15,967","11,953 to 15,967",10.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$72,683","$68,588","$76,778","$68,588 to $76,778"
12396,2014,6,6055,Napa County (CA),"137,324","12,317","10,207","14,427","10,207 to 14,427",9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$71,063","$66,853","$75,273","$66,853 to $75,273"
12397,2013,6,6055,Napa County (CA),"135,934","13,141","10,869","15,413","10,869 to 15,413",9.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$68,619","$65,099","$72,139","$65,099 to $72,139"
12398,2012,6,6055,Napa County (CA),"134,702","13,111","10,898","15,324","10,898 to 15,324",9.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$65,698","$61,873","$69,523","$61,873 to $69,523"
12399,2011,6,6055,Napa County (CA),"133,788","16,093","13,617","18,569","13,617 to 18,569",12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$61,179","$57,847","$64,511","$57,847 to $64,511"
12400,2010,6,6055,Napa County (CA),"132,538","14,189","11,771","16,607","11,771 to 16,607",10.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$62,893","$59,417","$66,369","$59,417 to $66,369"
15246,2015,6,6075,San Francisco County (CA),"849,842","105,244","98,137","112,351","98,137 to 112,351",12.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$90,527","$87,785","$93,269","$87,785 to $93,269"
15247,2014,6,6075,San Francisco County (CA),"837,036","101,313","94,708","107,918","94,708 to 107,918",12.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$83,788","$81,114","$86,462","$81,114 to $86,462"
15248,2013,6,6075,San Francisco County (CA),"822,030","113,217","106,286","120,148","106,286 to 120,148",13.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$76,933","$74,905","$78,961","$74,905 to $78,961"
15249,2012,6,6075,San Francisco County (CA),"810,697","120,702","113,150","128,254","113,150 to 128,254",14.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$72,093","$69,553","$74,633","$69,553 to $74,633"
15250,2011,6,6075,San Francisco County (CA),"797,283","110,260","101,507","119,013","101,507 to 119,013",13.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$69,354","$67,027","$71,681","$67,027 to $71,681"
15251,2010,6,6075,San Francisco County (CA),"789,928","100,910","92,005","109,815","92,005 to 109,815",12.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$70,883","$68,656","$73,110","$68,656 to $73,110"
15294,2015,6,6081,San Mateo County (CA),"758,807","63,663","58,517","68,809","58,517 to 68,809",8.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$101,133","$99,852","$102,414","$99,852 to $102,414"
15295,2014,6,6081,San Mateo County (CA),"752,259","56,580","50,164","62,996","50,164 to 62,996",7.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$100,806","$99,503","$102,109","$99,503 to $102,109"
15296,2013,6,6081,San Mateo County (CA),"740,909","58,932","52,734","65,130","52,734 to 65,130",8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$91,061","$89,450","$92,672","$89,450 to $92,672"
15297,2012,6,6081,San Mateo County (CA),"732,512","61,857","55,206","68,508","55,206 to 68,508",8.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$81,568","$79,865","$83,271","$79,865 to $83,271"
15298,2011,6,6081,San Mateo County (CA),"720,863","56,676","50,749","62,603","50,749 to 62,603",7.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$81,378","$78,428","$84,328","$78,428 to $84,328"
15299,2010,6,6081,San Mateo County (CA),"713,724","49,908","43,732","56,084","43,732 to 56,084",7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$82,413","$80,272","$84,554","$80,272 to $84,554"
15372,2015,6,6085,Santa Clara County (CA),"1,891,080","156,430","144,514","168,346","144,514 to 168,346",8.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$102,191","$100,870","$103,512","$100,870 to $103,512"
15373,2014,6,6085,Santa Clara County (CA),"1,867,602","159,553","146,664","172,442","146,664 to 172,442",8.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$97,219","$95,336","$99,102","$95,336 to $99,102"
15374,2013,6,6085,Santa Clara County (CA),"1,835,157","191,898","179,962","203,834","179,962 to 203,834",10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$91,843","$90,443","$93,243","$90,443 to $93,243"
15375,2012,6,6085,Santa Clara County (CA),"1,811,534","195,277","183,763","206,791","183,763 to 206,791",10.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$91,195","$89,948","$92,442","$89,948 to $92,442"
15376,2011,6,6085,Santa Clara County (CA),"1,782,850","190,005","178,932","201,078","178,932 to 201,078",10.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$84,741","$83,335","$86,147","$83,335 to $86,147"
15377,2010,6,6085,Santa Clara County (CA),"1,760,897","186,051","173,255","198,847","173,255 to 198,847",10.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$84,627","$82,907","$86,347","$82,907 to $86,347"
16019,2015,6,6095,Solano County (CA),"425,104","50,972","45,556","56,388","45,556 to 56,388",12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$67,202","$64,618","$69,786","$64,618 to $69,786"
16020,2014,6,6095,Solano County (CA),"420,019","51,638","45,698","57,578","45,698 to 57,578",12.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$67,106","$63,857","$70,355","$63,857 to $70,355"
16021,2013,6,6095,Solano County (CA),"413,335","53,441","48,268","58,614","48,268 to 58,614",12.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$63,398","$60,444","$66,352","$60,444 to $66,352"
16022,2012,6,6095,Solano County (CA),"409,125","58,170","53,830","62,510","53,830 to 62,510",14.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$61,976","$60,301","$63,651","$60,301 to $63,651"
16023,2011,6,6095,Solano County (CA),"404,109","54,912","49,437","60,387","49,437 to 60,387",13.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$63,090","$60,115","$66,065","$60,115 to $66,065"
16024,2010,6,6095,Solano County (CA),"401,865","49,159","43,660","54,658","43,660 to 54,658",12.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$62,948","$60,252","$65,644","$60,252 to $65,644"
16055,2015,6,6097,Sonoma County (CA),"493,876","54,563","49,610","59,516","49,610 to 59,516",11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$66,463","$63,924","$69,002","$63,924 to $69,002"
16056,2014,6,6097,Sonoma County (CA),"491,691","55,742","50,076","61,408","50,076 to 61,408",11.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$66,949","$64,082","$69,816","$64,082 to $69,816"
16057,2013,6,6097,Sonoma County (CA),"486,332","60,216","54,317","66,115","54,317 to 66,115",12.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$61,020","$59,502","$62,538","$59,502 to $62,538"
16058,2012,6,6097,Sonoma County (CA),"483,266","58,592","52,230","64,954","52,230 to 64,954",12.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$59,855","$57,909","$61,801","$57,909 to $61,801"
16059,2011,6,6097,Sonoma County (CA),"480,144","58,394","52,472","64,316","52,472 to 64,316",12.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$60,792","$59,023","$62,561","$59,023 to $62,561"
16060,2010,6,6097,Sonoma County (CA),"477,075","60,909","55,013","66,805","55,013 to 66,805",12.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$58,703","$55,842","$61,564","$55,842 to $61,564"

In [21]:
CA_Household_Income_df = CA_Household_Income_df.drop_duplicates()
CA_Household_Income_df

,Year,State,County ID,State / County Name,All Ages SAIPE Poverty Universe,All Ages in Poverty Count,All Ages in Poverty Count LB 90%,All Ages in Poverty Count UB 90%,90% Confidence Interval (All Ages in Poverty Count),All Ages in Poverty Percent,...,Under Age 5 in Poverty Count UB 90%,90% Confidence Interval (Under Age 5 in Poverty Count),Under Age 5 in Poverty Percent,Under Age 5 in Poverty Percent LB 90%,Under Age 5 in Poverty Percent UB 90%,90% Confidence Interval (Under Age 5 in Poverty Percent),Median Household Income in Dollars,Median Household Income in Dollars LB 90%,Median Household Income in Dollars UB 90%,90% Confidence Interval (Median Household Income in Dollars)
156,2015,6,6001,Alameda County (CA),"1,609,162","184,716","172,690","196,742","172,690 to 196,742",11.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$81,462","$80,249","$82,675","$80,249 to $82,675"
157,2014,6,6001,Alameda County (CA),"1,581,548","197,984","186,953","209,015","186,953 to 209,015",12.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$76,996","$75,788","$78,204","$75,788 to $78,204"
158,2013,6,6001,Alameda County (CA),"1,549,789","201,303","189,228","213,378","189,228 to 213,378",13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$72,128","$70,566","$73,690","$70,566 to $73,690"
159,2012,6,6001,Alameda County (CA),"1,526,032","200,101","189,366","210,836","189,366 to 210,836",13.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$70,209","$68,893","$71,525","$68,893 to $71,525"
160,2011,6,6001,Alameda County (CA),"1,500,076","198,382","185,035","211,729","185,035 to 211,729",13.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$67,295","$65,680","$68,910","$65,680 to $68,910"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19127,2014,6,6115,Yuba County (CA),"72,768","15,693","13,360","18,026","13,360 to 18,026",21.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$41,403","$37,739","$45,067","$37,739 to $45,067"
19128,2013,6,6115,Yuba County (CA),"72,122","14,876","12,609","17,143","12,609 to 17,143",20.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$41,824","$38,572","$45,076","$38,572 to $45,076"
19129,2012,6,6115,Yuba County (CA),"71,760","16,075","13,960","18,190","13,960 to 18,190",22.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$41,599","$38,915","$44,283","$38,915 to $44,283"
19130,2011,6,6115,Yuba County (CA),"71,383","13,982","11,451","16,513","11,451 to 16,513",19.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$43,299","$41,651","$44,947","$41,651 to $44,947"
19131,2010,6,6115,Yuba County (CA),"71,175","14,708","12,230","17,186","12,230 to 17,186",20.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$41,045","$37,598","$44,492","$37,598 to $44,492"

In [45]:

SF_CA_Household_Income_df = SF_CA_Income_df.loc[:, ["Year", "State / County Name", "Median Household Income in Dollars"]]
SF_CA_Household_Income_df.head()

     Year  State / County Name Median Household Income in Dollars
156  2015  Alameda County (CA)                           $81,462
157  2014  Alameda County (CA)                           $76,996
158  2013  Alameda County (CA)                           $72,128
159  2012  Alameda County (CA)                           $70,209
160  2011  Alameda County (CA)                           $67,295

In [46]:
SF_CA_Household_Income_df.dropna(how="any")

       Year        State / County Name Median Household Income in Dollars
156    2015        Alameda County (CA)                           $81,462
157    2014        Alameda County (CA)                           $76,996
158    2013        Alameda County (CA)                           $72,128
159    2012        Alameda County (CA)                           $70,209
160    2011        Alameda County (CA)                           $67,295
161    2010        Alameda County (CA)                           $66,937
3790   2015   Contra Costa County (CA)                           $83,036
3791   2014   Contra Costa County (CA)                           $80,338
3792   2013   Contra Costa County (CA)                           $78,909
3793   2012   Contra Costa County (CA)                           $74,208
3794   2011   Contra Costa County (CA)                           $74,241
3795   2010   Contra Costa County (CA)                           $73,678
10835  2015          Marin County (CA)                           $99,868
10836  2014          Marin County (CA)                           $94,549
10837  2013          Marin County (CA)                           $94,347
10838  2012          Marin County (CA)                           $88,654
10839  2011          Marin County (CA)                           $78,470
10840  2010          Marin County (CA)                           $82,383
12395  2015           Napa County (CA)                           $72,683
12396  2014           Napa County (CA)                           $71,063
12397  2013           Napa County (CA)                           $68,619
12398  2012           Napa County (CA)                           $65,698
12399  2011           Napa County (CA)                           $61,179
12400  2010           Napa County (CA)                           $62,893
15246  2015  San Francisco County (CA)                           $90,527
15247  2014  San Francisco County (CA)                           $83,788
15248  2013  San Francisco County (CA)                           $76,933
15249  2012  San Francisco County (CA)                           $72,093
15250  2011  San Francisco County (CA)                           $69,354
15251  2010  San Francisco County (CA)                           $70,883
15294  2015      San Mateo County (CA)                          $101,133
15295  2014      San Mateo County (CA)                          $100,806
15296  2013      San Mateo County (CA)                           $91,061
15297  2012      San Mateo County (CA)                           $81,568
15298  2011      San Mateo County (CA)                           $81,378
15299  2010      San Mateo County (CA)                           $82,413
15372  2015    Santa Clara County (CA)                          $102,191
15373  2014    Santa Clara County (CA)                           $97,219
15374  2013    Santa Clara County (CA)                           $91,843
15375  2012    Santa Clara County (CA)                           $91,195
15376  2011    Santa Clara County (CA)                           $84,741
15377  2010    Santa Clara County (CA)                           $84,627
16019  2015         Solano County (CA)                           $67,202
16020  2014         Solano County (CA)                           $67,106
16021  2013         Solano County (CA)                           $63,398
16022  2012         Solano County (CA)                           $61,976
16023  2011         Solano County (CA)                           $63,090
16024  2010         Solano County (CA)                           $62,948
16055  2015         Sonoma County (CA)                           $66,463
16056  2014         Sonoma County (CA)                           $66,949
16057  2013         Sonoma County (CA)                           $61,020
16058  2012         Sonoma County (CA)                           $59,855
16059  2011         Sonoma County (CA)                           $60,792
16060  2010         Sonoma County (CA)                           $58,703

In [47]:
# Take $ sign off to calculate mean values 
SF_CA_Household_Income_df["Median Household Income"] = SF_CA_Household_Income_df["Median Household Income in Dollars"].str.replace('$', '').str.replace(',', '')
SF_CA_Household_Income_df["Median Household Income"] = pd.to_numeric(SF_CA_Household_Income_df["Median Household Income"])
SF_CA_Household_Income_df["Median Household Income"]

156       81462
157       76996
158       72128
159       70209
160       67295
161       66937
3790      83036
3791      80338
3792      78909
3793      74208
3794      74241
3795      73678
10835     99868
10836     94549
10837     94347
10838     88654
10839     78470
10840     82383
12395     72683
12396     71063
12397     68619
12398     65698
12399     61179
12400     62893
15246     90527
15247     83788
15248     76933
15249     72093
15250     69354
15251     70883
15294    101133
15295    100806
15296     91061
15297     81568
15298     81378
15299     82413
15372    102191
15373     97219
15374     91843
15375     91195
15376     84741
15377     84627
16019     67202
16020     67106
16021     63398
16022     61976
16023     63090
16024     62948
16055     66463
16056     66949
16057     61020
16058     59855
16059     60792
16060     58703
Name: Median Household Income, dtype: int64

In [48]:
SF_CA_Household_Income_df.head()

,Year,State / County Name,Median Household Income in Dollars,Median Household Income
156,2015,Alameda County (CA),"$81,462",81462
157,2014,Alameda County (CA),"$76,996",76996
158,2013,Alameda County (CA),"$72,128",72128
159,2012,Alameda County (CA),"$70,209",70209
160,2011,Alameda County (CA),"$67,295",67295

In [49]:

SF_County_Income_df = SF_CA_Household_Income_df.groupby(["State / County Name"])
SF_County_Income_df.head()

,Year,State / County Name,Median Household Income in Dollars,Median Household Income
156,2015,Alameda County (CA),"$81,462",81462
157,2014,Alameda County (CA),"$76,996",76996
158,2013,Alameda County (CA),"$72,128",72128
159,2012,Alameda County (CA),"$70,209",70209
160,2011,Alameda County (CA),"$67,295",67295
3790,2015,Contra Costa County (CA),"$83,036",83036
3791,2014,Contra Costa County (CA),"$80,338",80338
3792,2013,Contra Costa County (CA),"$78,909",78909
3793,2012,Contra Costa County (CA),"$74,208",74208
3794,2011,Contra Costa County (CA),"$74,241",74241
10835,2015,Marin County (CA),"$99,868",99868
10836,2014,Marin County (CA),"$94,549",94549
10837,2013,Marin County (CA),"$94,347",94347
10838,2012,Marin County (CA),"$88,654",88654
10839,2011,Marin County (CA),"$78,470",78470
12395,2015,Napa County (CA),"$72,683",72683
12396,2014,Napa County (CA),"$71,063",71063
12397,2013,Napa County (CA),"$68,619",68619
12398,2012,Napa County (CA),"$65,698",65698
12399,2011,Napa County (CA),"$61,179",61179
15246,2015,San Francisco County (CA),"$90,527",90527
15247,2014,San Francisco County (CA),"$83,788",83788
15248,2013,San Francisco County (CA),"$76,933",76933
15249,2012,San Francisco County (CA),"$72,093",72093
15250,2011,San Francisco County (CA),"$69,354",69354
15294,2015,San Mateo County (CA),"$101,133",101133
15295,2014,San Mateo County (CA),"$100,806",100806
15296,2013,San Mateo County (CA),"$91,061",91061
15297,2012,San Mateo County (CA),"$81,568",81568
15298,2011,San Mateo County (CA),"$81,378",81378
15372,2015,Santa Clara County (CA),"$102,191",102191
15373,2014,Santa Clara County (CA),"$97,219",97219
15374,2013,Santa Clara County (CA),"$91,843",91843
15375,2012,Santa Clara County (CA),"$91,195",91195
15376,2011,Santa Clara County (CA),"$84,741",84741
16019,2015,Solano County (CA),"$67,202",67202
16020,2014,Solano County (CA),"$67,106",67106
16021,2013,Solano County (CA),"$63,398",63398
16022,2012,Solano County (CA),"$61,976",61976
16023,2011,Solano County (CA),"$63,090",63090
16055,2015,Sonoma County (CA),"$66,463",66463
16056,2014,Sonoma County (CA),"$66,949",66949
16057,2013,Sonoma County (CA),"$61,020",61020
16058,2012,Sonoma County (CA),"$59,855",59855
16059,2011,Sonoma County (CA),"$60,792",60792

In [54]:
# SanFrancisco  county info summary 
SF_County_Income_df.describe()

                           Year                                             \
                          count    mean       std     min      25%     50%
State / County Name
Alameda County (CA)         6.0  2012.5  1.870829  2010.0  2011.25  2012.5
Contra Costa County (CA)    6.0  2012.5  1.870829  2010.0  2011.25  2012.5
Marin County (CA)           6.0  2012.5  1.870829  2010.0  2011.25  2012.5
Napa County (CA)            6.0  2012.5  1.870829  2010.0  2011.25  2012.5
San Francisco County (CA)   6.0  2012.5  1.870829  2010.0  2011.25  2012.5
San Mateo County (CA)       6.0  2012.5  1.870829  2010.0  2011.25  2012.5
Santa Clara County (CA)     6.0  2012.5  1.870829  2010.0  2011.25  2012.5
Solano County (CA)          6.0  2012.5  1.870829  2010.0  2011.25  2012.5
Sonoma County (CA)          6.0  2012.5  1.870829  2010.0  2011.25  2012.5

                                           Median Household Income  \
                               75%     max                   count
State / County Name
Alameda County (CA)        2013.75  2015.0                     6.0
Contra Costa County (CA)   2013.75  2015.0                     6.0
Marin County (CA)          2013.75  2015.0                     6.0
Napa County (CA)           2013.75  2015.0                     6.0
San Francisco County (CA)  2013.75  2015.0                     6.0
San Mateo County (CA)      2013.75  2015.0                     6.0
Santa Clara County (CA)    2013.75  2015.0                     6.0
Solano County (CA)         2013.75  2015.0                     6.0
Sonoma County (CA)         2013.75  2015.0                     6.0

                                                                         \
                                   mean          std      min       25%
State / County Name
Alameda County (CA)        72504.500000  5726.384505  66937.0  68023.50
Contra Costa County (CA)   77401.666667  3916.499287  73678.0  74216.25
Marin County (CA)          89711.833333  8114.681742  78470.0  83950.75
Napa County (CA)           67022.500000  4557.834475  61179.0  63594.25
San Francisco County (CA)  77263.000000  8349.895832  69354.0  71185.50
San Mateo County (CA)      89726.500000  9427.516211  81378.0  81779.25
Santa Clara County (CA)    91969.333333  6911.087951  84627.0  86354.50
Solano County (CA)         64286.666667  2271.596678  61976.0  62983.50
Sonoma County (CA)         62297.000000  3514.900112  58703.0  60089.25


                               50%       75%       max
State / County Name
Alameda County (CA)        71168.5  75779.00   81462.0
Contra Costa County (CA)   76575.0  79980.75   83036.0
Marin County (CA)          91500.5  94498.50   99868.0
Napa County (CA)           67158.5  70452.00   72683.0
San Francisco County (CA)  74513.0  82074.25   90527.0
San Mateo County (CA)      86737.0  98369.75  101133.0
Santa Clara County (CA)    91519.0  95875.00  102191.0
Solano County (CA)         63244.0  66179.00   67202.0
Sonoma County (CA)         60906.0  65102.25   66949.0

In [55]:

SF_CA_Average_HouseHold_income  = SF_County_Income_df["Median Household Income"].mean()
SF_CA_Average_HouseHold_income

State / County Name
Alameda County (CA)          72504.500000
Contra Costa County (CA)     77401.666667
Marin County (CA)            89711.833333
Napa County (CA)             67022.500000
San Francisco County (CA)    77263.000000
San Mateo County (CA)        89726.500000
Santa Clara County (CA)      91969.333333
Solano County (CA)           64286.666667
Sonoma County (CA)           62297.000000
Name: Median Household Income, dtype: float64

# Louisiana Data Analysis