In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census

In [2]:
csv_file = '../green_city/medianHouseholdIncome.csv'
csv_file

'../green_city/medianHouseholdIncome.csv'

In [3]:
Household_Income_df = pd.read_csv(csv_file)

In [4]:
Household_Income_df["State / County Name"].value_counts()

Crawford County (KS)           6
Cerro Gordo County (IA)        6
Jackson County (MN)            6
Coahoma County (MS)            6
Grant County (KS)              6
                              ..
Bedford city (VA)              4
Petersburg Census Area (AK)    4
Petersburg Borough (AK)        2
Kusilvak Census Area (AK)      1
Oglala Lakota County (SD)      1
Name: State / County Name, Length: 3198, dtype: int64

In [5]:
#"PA" is Pennsylvania
PA_Household_Income_df = Household_Income_df.loc[(Household_Income_df["State"]==42)]

In [6]:
PA_Household_Income_df["State / County Name"].value_counts(ascending=False)

Luzerne County (PA)         6
Schuylkill County (PA)      6
Bucks County (PA)           6
Delaware County (PA)        6
Snyder County (PA)          6
                           ..
Venango County (PA)         6
Chester County (PA)         6
Clarion County (PA)         6
Philadelphia County (PA)    6
Cameron County (PA)         6
Name: State / County Name, Length: 68, dtype: int64

In [7]:
#Counties included in Pittsburgh metro area
Pitt_PA_Income_df = PA_Household_Income_df.loc[(PA_Household_Income_df["State / County Name"]=="Allegheny County (PA)") | (PA_Household_Income_df["State / County Name"]=="Beaver County (PA)") | (PA_Household_Income_df["State / County Name"]=="Butler County (PA)") | (PA_Household_Income_df["State / County Name"]=="Washington County (PA)") | (PA_Household_Income_df["State / County Name"]=="Westmoreland County (PA)")]
Pitt_PA_Income_df

,Year,State,County ID,State / County Name,All Ages SAIPE Poverty Universe,All Ages in Poverty Count,All Ages in Poverty Count LB 90%,All Ages in Poverty Count UB 90%,90% Confidence Interval (All Ages in Poverty Count),All Ages in Poverty Percent,...,Under Age 5 in Poverty Count UB 90%,90% Confidence Interval (Under Age 5 in Poverty Count),Under Age 5 in Poverty Percent,Under Age 5 in Poverty Percent LB 90%,Under Age 5 in Poverty Percent UB 90%,90% Confidence Interval (Under Age 5 in Poverty Percent),Median Household Income in Dollars,Median Household Income in Dollars LB 90%,Median Household Income in Dollars UB 90%,90% Confidence Interval (Median Household Income in Dollars)
282,2015,42,42003,Allegheny County (PA),"1,195,809","145,454","136,505","154,403","136,505 to 154,403",12.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$54,412","$52,916","$55,908","$52,916 to $55,908"
283,2014,42,42003,Allegheny County (PA),"1,196,677","157,151","148,841","165,461","148,841 to 165,461",13.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$52,385","$51,464","$53,306","$51,464 to $53,306"
284,2013,42,42003,Allegheny County (PA),"1,197,357","161,788","153,128","170,448","153,128 to 170,448",13.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$51,400","$50,688","$52,112","$50,688 to $52,112"
285,2012,42,42003,Allegheny County (PA),"1,196,361","151,371","141,802","160,940","141,802 to 160,940",12.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$50,831","$50,056","$51,606","$50,056 to $51,606"
286,2011,42,42003,Allegheny County (PA),"1,193,487","159,663","148,936","170,390","148,936 to 170,390",13.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$49,682","$48,640","$50,724","$48,640 to $50,724"
287,2010,42,42003,Allegheny County (PA),"1,190,891","141,453","130,928","151,978","130,928 to 151,978",11.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$47,490","$46,388","$48,592","$46,388 to $48,592"
984,2015,42,42007,Beaver County (PA),"165,873","21,668","18,958","24,378","18,958 to 24,378",13.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$50,131","$47,165","$53,097","$47,165 to $53,097"
985,2014,42,42007,Beaver County (PA),"166,375","19,507","16,881","22,133","16,881 to 22,133",11.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$51,041","$49,668","$52,414","$49,668 to $52,414"
986,2013,42,42007,Beaver County (PA),"167,021","18,948","15,990","21,906","15,990 to 21,906",11.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$49,215","$46,769","$51,661","$46,769 to $51,661"
987,2012,42,42007,Beaver County (PA),"167,291","20,088","16,980","23,196","16,980 to 23,196",12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,"$46,933","$44,086","$49,780","$44,086 to $49,780"
988,2011,42,42007,Beaver County (PA),"167,212","20,541","18,056","23,026","18,056 to 23,026",12.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$48,140","$45,840","$50,440","$45,840 to $50,440"
989,2010,42,42007,Beaver County (PA),"167,466","25,211","22,355","28,067","22,355 to 28,067",15.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$44,020","$42,044","$45,996","$42,044 to $45,996"
2002,2015,42,42019,Butler County (PA),"181,237","17,265","14,887","19,643","14,887 to 19,643",9.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$67,892","$65,149","$70,635","$65,149 to $70,635"
2003,2014,42,42019,Butler County (PA),"180,799","16,152","13,596","18,708","13,596 to 18,708",8.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$60,851","$58,263","$63,439","$58,263 to $63,439"
2004,2013,42,42019,Butler County (PA),"180,169","16,901","14,734","19,068","14,734 to 19,068",9.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$58,430","$55,830","$61,030","$55,830 to $61,030"
2005,2012,42,42019,Butler County (PA),"179,792","17,255","14,973","19,537","14,973 to 19,537",9.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$57,346","$54,587","$60,105","$54,587 to $60,105"
2006,2011,42,42019,Butler County (PA),"179,668","15,985","13,597","18,373","13,597 to 18,373",8.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$54,888","$52,687","$57,089","$52,687 to $57,089"
2007,2010,42,42019,Butler County (PA),"178,819","16,542","13,763","19,321","13,763 to 19,321",9.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$54,363","$51,659","$57,067","$51,659 to $57,067"
18124,2015,42,42125,Washington County (PA),"202,922","20,501","17,840","23,162","17,840 to 23,162",10.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$57,622","$54,538","$60,706","$54,538 to $60,706"
18125,2014,42,42125,Washington County (PA),"202,822","21,640","18,637","24,643","18,637 to 24,643",10.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$55,796","$53,374","$58,218","$53,374 to $58,218"
18126,2013,42,42125,Washington County (PA),"202,783","22,123","19,083","25,163","19,083 to 25,163",10.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$54,919","$53,163","$56,675","$53,163 to $56,675"
18127,2012,42,42125,Washington County (PA),"203,161","21,914","19,082","24,746","19,082 to 24,746",10.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$53,545","$51,167","$55,923","$51,167 to $55,923"
18128,2011,42,42125,Washington County (PA),"202,728","21,479","18,853","24,105","18,853 to 24,105",10.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$52,384","$50,352","$54,416","$50,352 to $54,416"
18129,2010,42,42125,Washington County (PA),"202,264","21,380","18,343","24,417","18,343 to 24,417",10.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$47,823","$45,182","$50,464","$45,182 to $50,464"
18442,2015,42,42129,Westmoreland County (PA),"351,293","39,587","35,219","43,955","35,219 to 43,955",11.3,...,NaN,NaN,NaN,NaN,NaN,NaN,"$53,422","$51,443","$55,401","$51,443 to $55,401"
18443,2014,42,42129,Westmoreland County (PA),"352,744","35,717","31,509","39,925","31,509 to 39,925",10.1,...,NaN,NaN,NaN,NaN,NaN,NaN,"$53,536","$51,600","$55,472","$51,600 to $55,472"
18444,2013,42,42129,Westmoreland County (PA),"354,607","38,016","33,591","42,441","33,591 to 42,441",10.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$51,412","$50,013","$52,811","$50,013 to $52,811"
18445,2012,42,42129,Westmoreland County (PA),"355,755","38,648","34,604","42,692","34,604 to 42,692",10.9,...,NaN,NaN,NaN,NaN,NaN,NaN,"$49,642","$47,978","$51,306","$47,978 to $51,306"
18446,2011,42,42129,Westmoreland County (PA),"357,008","37,877","33,368","42,386","33,368 to 42,386",10.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$46,630","$45,085","$48,175","$45,085 to $48,175"
18447,2010,42,42129,Westmoreland County (PA),"357,446","37,017","32,440","41,594","32,440 to 41,594",10.4,...,NaN,NaN,NaN,NaN,NaN,NaN,"$46,468","$44,659","$48,277","$44,659 to $48,277"

In [8]:
PA_Household_Income_df = PA_Household_Income_df.drop_duplicates()
PA_Household_Income_df

,Year,State,County ID,State / County Name,All Ages SAIPE Poverty Universe,All Ages in Poverty Count,All Ages in Poverty Count LB 90%,All Ages in Poverty Count UB 90%,90% Confidence Interval (All Ages in Poverty Count),All Ages in Poverty Percent,...,Under Age 5 in Poverty Count UB 90%,90% Confidence Interval (Under Age 5 in Poverty Count),Under Age 5 in Poverty Percent,Under Age 5 in Poverty Percent LB 90%,Under Age 5 in Poverty Percent UB 90%,90% Confidence Interval (Under Age 5 in Poverty Percent),Median Household Income in Dollars,Median Household Income in Dollars LB 90%,Median Household Income in Dollars UB 90%,90% Confidence Interval (Median Household Income in Dollars)
102,2015,42,42001,Adams County (PA),"98,151","8,365","6,901","9,829","6,901 to 9,829",8.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$60,558","$58,014","$63,102","$58,014 to $63,102"
103,2014,42,42001,Adams County (PA),"97,527","10,492","9,027","11,957","9,027 to 11,957",10.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$60,179","$57,548","$62,810","$57,548 to $62,810"
104,2013,42,42001,Adams County (PA),"97,290","9,289","7,570","11,008","7,570 to 11,008",9.5,...,NaN,NaN,NaN,NaN,NaN,NaN,"$57,725","$55,109","$60,341","$55,109 to $60,341"
105,2012,42,42001,Adams County (PA),"97,308","9,552","8,040","11,064","8,040 to 11,064",9.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$57,919","$55,020","$60,818","$55,020 to $60,818"
106,2011,42,42001,Adams County (PA),"97,292","8,451","6,974","9,928","6,974 to 9,928",8.7,...,NaN,NaN,NaN,NaN,NaN,NaN,"$54,460","$52,056","$56,864","$52,056 to $56,864"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19103,2014,42,42133,York County (PA),"431,614","44,232","38,780","49,684","38,780 to 49,684",10.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$58,471","$56,478","$60,464","$56,478 to $60,464"
19104,2013,42,42133,York County (PA),"429,642","46,480","41,219","51,741","41,219 to 51,741",10.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$56,963","$55,076","$58,850","$55,076 to $58,850"
19105,2012,42,42133,York County (PA),"428,821","45,462","40,528","50,396","40,528 to 50,396",10.6,...,NaN,NaN,NaN,NaN,NaN,NaN,"$55,646","$54,194","$57,098","$54,194 to $57,098"
19106,2011,42,42133,York County (PA),"427,903","46,355","40,929","51,781","40,929 to 51,781",10.8,...,NaN,NaN,NaN,NaN,NaN,NaN,"$55,521","$54,133","$56,909","$54,133 to $56,909"
19107,2010,42,42133,York County (PA),"426,623","39,408","34,999","43,817","34,999 to 43,817",9.2,...,NaN,NaN,NaN,NaN,NaN,NaN,"$55,960","$53,659","$58,261","$53,659 to $58,261"

In [9]:
Pitt_PA_Household_Income_df = Pitt_PA_Income_df.loc[:, ["Year", "State / County Name", "Median Household Income in Dollars"]]
Pitt_PA_Household_Income_df

       Year       State / County Name Median Household Income in Dollars
282    2015     Allegheny County (PA)                           $54,412
283    2014     Allegheny County (PA)                           $52,385
284    2013     Allegheny County (PA)                           $51,400
285    2012     Allegheny County (PA)                           $50,831
286    2011     Allegheny County (PA)                           $49,682
287    2010     Allegheny County (PA)                           $47,490
984    2015        Beaver County (PA)                           $50,131
985    2014        Beaver County (PA)                           $51,041
986    2013        Beaver County (PA)                           $49,215
987    2012        Beaver County (PA)                           $46,933
988    2011        Beaver County (PA)                           $48,140
989    2010        Beaver County (PA)                           $44,020
2002   2015        Butler County (PA)                           $67,892
2003   2014        Butler County (PA)                           $60,851
2004   2013        Butler County (PA)                           $58,430
2005   2012        Butler County (PA)                           $57,346
2006   2011        Butler County (PA)                           $54,888
2007   2010        Butler County (PA)                           $54,363
18124  2015    Washington County (PA)                           $57,622
18125  2014    Washington County (PA)                           $55,796
18126  2013    Washington County (PA)                           $54,919
18127  2012    Washington County (PA)                           $53,545
18128  2011    Washington County (PA)                           $52,384
18129  2010    Washington County (PA)                           $47,823
18442  2015  Westmoreland County (PA)                           $53,422
18443  2014  Westmoreland County (PA)                           $53,536
18444  2013  Westmoreland County (PA)                           $51,412
18445  2012  Westmoreland County (PA)                           $49,642
18446  2011  Westmoreland County (PA)                           $46,630
18447  2010  Westmoreland County (PA)                           $46,468

In [10]:
Pitt_PA_Household_Income_df.dropna(how="any")

       Year       State / County Name Median Household Income in Dollars
282    2015     Allegheny County (PA)                           $54,412
283    2014     Allegheny County (PA)                           $52,385
284    2013     Allegheny County (PA)                           $51,400
285    2012     Allegheny County (PA)                           $50,831
286    2011     Allegheny County (PA)                           $49,682
287    2010     Allegheny County (PA)                           $47,490
984    2015        Beaver County (PA)                           $50,131
985    2014        Beaver County (PA)                           $51,041
986    2013        Beaver County (PA)                           $49,215
987    2012        Beaver County (PA)                           $46,933
988    2011        Beaver County (PA)                           $48,140
989    2010        Beaver County (PA)                           $44,020
2002   2015        Butler County (PA)                           $67,892
2003   2014        Butler County (PA)                           $60,851
2004   2013        Butler County (PA)                           $58,430
2005   2012        Butler County (PA)                           $57,346
2006   2011        Butler County (PA)                           $54,888
2007   2010        Butler County (PA)                           $54,363
18124  2015    Washington County (PA)                           $57,622
18125  2014    Washington County (PA)                           $55,796
18126  2013    Washington County (PA)                           $54,919
18127  2012    Washington County (PA)                           $53,545
18128  2011    Washington County (PA)                           $52,384
18129  2010    Washington County (PA)                           $47,823
18442  2015  Westmoreland County (PA)                           $53,422
18443  2014  Westmoreland County (PA)                           $53,536
18444  2013  Westmoreland County (PA)                           $51,412
18445  2012  Westmoreland County (PA)                           $49,642
18446  2011  Westmoreland County (PA)                           $46,630
18447  2010  Westmoreland County (PA)                           $46,468

In [11]:
# Take $ sign off to calculate mean values 
Pitt_PA_Household_Income_df["Median Household Income"] = Pitt_PA_Household_Income_df["Median Household Income in Dollars"].str.replace('$', '').str.replace(',', '')
Pitt_PA_Household_Income_df["Median Household Income"] = pd.to_numeric(Pitt_PA_Household_Income_df["Median Household Income"])
Pitt_PA_Household_Income_df["Median Household Income"]

282      54412
283      52385
284      51400
285      50831
286      49682
287      47490
984      50131
985      51041
986      49215
987      46933
988      48140
989      44020
2002     67892
2003     60851
2004     58430
2005     57346
2006     54888
2007     54363
18124    57622
18125    55796
18126    54919
18127    53545
18128    52384
18129    47823
18442    53422
18443    53536
18444    51412
18445    49642
18446    46630
18447    46468
Name: Median Household Income, dtype: int64

In [12]:
Pitt_County_Income_df = Pitt_PA_Household_Income_df.groupby(["State / County Name"])
Pitt_County_Income_df.head()

,Year,State / County Name,Median Household Income in Dollars,Median Household Income
282,2015,Allegheny County (PA),"$54,412",54412
283,2014,Allegheny County (PA),"$52,385",52385
284,2013,Allegheny County (PA),"$51,400",51400
285,2012,Allegheny County (PA),"$50,831",50831
286,2011,Allegheny County (PA),"$49,682",49682
984,2015,Beaver County (PA),"$50,131",50131
985,2014,Beaver County (PA),"$51,041",51041
986,2013,Beaver County (PA),"$49,215",49215
987,2012,Beaver County (PA),"$46,933",46933
988,2011,Beaver County (PA),"$48,140",48140
2002,2015,Butler County (PA),"$67,892",67892
2003,2014,Butler County (PA),"$60,851",60851
2004,2013,Butler County (PA),"$58,430",58430
2005,2012,Butler County (PA),"$57,346",57346
2006,2011,Butler County (PA),"$54,888",54888
18124,2015,Washington County (PA),"$57,622",57622
18125,2014,Washington County (PA),"$55,796",55796
18126,2013,Washington County (PA),"$54,919",54919
18127,2012,Washington County (PA),"$53,545",53545
18128,2011,Washington County (PA),"$52,384",52384
18442,2015,Westmoreland County (PA),"$53,422",53422
18443,2014,Westmoreland County (PA),"$53,536",53536
18444,2013,Westmoreland County (PA),"$51,412",51412
18445,2012,Westmoreland County (PA),"$49,642",49642
18446,2011,Westmoreland County (PA),"$46,630",46630

In [13]:
#need to fix this?  because of year?
Pitt_County_Income_df.describe()

                          Year                                             \
                         count    mean       std     min      25%     50%
State / County Name
Allegheny County (PA)      6.0  2012.5  1.870829  2010.0  2011.25  2012.5
Beaver County (PA)         6.0  2012.5  1.870829  2010.0  2011.25  2012.5
Butler County (PA)         6.0  2012.5  1.870829  2010.0  2011.25  2012.5
Washington County (PA)     6.0  2012.5  1.870829  2010.0  2011.25  2012.5
Westmoreland County (PA)   6.0  2012.5  1.870829  2010.0  2011.25  2012.5

                                          Median Household Income  \
                              75%     max                   count
State / County Name
Allegheny County (PA)     2013.75  2015.0                     6.0
Beaver County (PA)        2013.75  2015.0                     6.0
Butler County (PA)        2013.75  2015.0                     6.0
Washington County (PA)    2013.75  2015.0                     6.0
Westmoreland County (PA)  2013.75  2015.0                     6.0

                                                                        \
                                  mean          std      min       25%
State / County Name
Allegheny County (PA)     51033.333333  2357.926519  47490.0  49969.25
Beaver County (PA)        48246.666667  2525.806379  44020.0  47234.75
Butler County (PA)        58961.666667  4979.075764  54363.0  55502.50
Washington County (PA)    53681.500000  3392.763402  47823.0  52674.25
Westmoreland County (PA)  50185.000000  3161.071401  46468.0  47383.00


                              50%       75%      max
State / County Name
Allegheny County (PA)     51115.5  52138.75  54412.0
Beaver County (PA)        48677.5  49902.00  51041.0
Butler County (PA)        57888.0  60245.75  67892.0
Washington County (PA)    54232.0  55576.75  57622.0
Westmoreland County (PA)  50527.0  52919.50  53536.0

In [14]:
Pitt_PA_Average_HouseHold_income  = Pitt_County_Income_df["Median Household Income"].mean()
Pitt_PA_Average_HouseHold_income

State / County Name
Allegheny County (PA)       51033.333333
Beaver County (PA)          48246.666667
Butler County (PA)          58961.666667
Washington County (PA)      53681.500000
Westmoreland County (PA)    50185.000000
Name: Median Household Income, dtype: float64

In [21]:
#median hh income combined for 2010-2015 for each individual county in Pittsburgh metro 
Pitt_county_avgs = pd.DataFrame(Pitt_PA_Average_HouseHold_income)
Pitt_county_avgs

                          Median Household Income
State / County Name
Allegheny County (PA)                51033.333333
Beaver County (PA)                   48246.666667
Butler County (PA)                   58961.666667
Washington County (PA)               53681.500000
Westmoreland County (PA)             50185.000000

In [22]:
#Calculate the mdedian hh income average for all of the Pittsburgh metro counties combined
Total_Pitt_avg = Pitt_county_avgs["Median Household Income"].mean()
Total_Pitt_avg

52421.63333333333

In [ ]:
Pitt_PA_Average_HouseHold_income.to_csv("Pitt_Median_Income.csv")

In [ ]:
#create line graph showing???
# Create the X and Y axis lists