In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import matplotlib
matplotlib.style.use('ggplot')

from census import Census

import scipy.stats as st
from scipy.stats import linregress
from scipy.stats import sem

import seaborn as sns

In [2]:
csv1 = '../Resources/Visu_Income_All_Cities.csv'
csv2 = '../Resources/Visu_Life_All_Cities.csv'

In [3]:
life_df = pd.read_csv(csv2)
Income_df = pd.read_csv(csv1)

In [4]:
life_df.head()

        State              County  Life Expectancy
0  California  Alameda County, CA             87.2
1  California  Alameda County, CA             81.5
2  California  Alameda County, CA             87.2
3  California  Alameda County, CA             82.9
4  California  Alameda County, CA             78.8

In [5]:
Income_df.head()

,Year,State / County Name,Median Household Income in Dollars,All Ages in Poverty Percent,Median Household Income
0,2015,Allegheny County (PA),"$54,412",12.2,54412
1,2014,Allegheny County (PA),"$52,385",13.1,52385
2,2013,Allegheny County (PA),"$51,400",13.5,51400
3,2012,Allegheny County (PA),"$50,831",12.7,50831
4,2011,Allegheny County (PA),"$49,682",13.4,49682

In [6]:
life_County_df = life_df.groupby(["County"])
life_County_df.head()

             State                   County  Life Expectancy
0       California       Alameda County, CA             87.2
1       California       Alameda County, CA             81.5
2       California       Alameda County, CA             87.2
3       California       Alameda County, CA             82.9
4       California       Alameda County, CA             78.8
...            ...                      ...              ...
2127  Pennsylvania  Westmoreland County, PA             68.9
2128  Pennsylvania  Westmoreland County, PA             75.9
2129  Pennsylvania  Westmoreland County, PA             75.5
2130  Pennsylvania  Westmoreland County, PA             74.8
2131  Pennsylvania  Westmoreland County, PA             79.0

[109 rows x 3 columns]

In [7]:
#Income_df['County'] = Income_df['State / County Name'].str.replace('Allegheny County (PA)', 'Allegheny County, PA')
#Income_df['County'] = Income_df['State / County Name'].str.replace('(CA)', ', CA')
#Income_df['County'] = Income_df['State / County Name'].str.replace('(LA)', ', LA')

In [21]:
final_life = life_County_df["Life Expectancy"].mean()
final_life

County
Alameda County, CA             80.845858
Allegheny County, PA           77.236134
Ascension Parish, LA           78.400000
Beaver County, PA              77.204000
Butler County, PA              78.867442
Contra Costa County, CA        80.813333
East Baton Rouge Parish, LA    74.965432
East Feliciana Parish, LA      76.000000
Iberville Parish, LA           74.028571
Livingston Parish, LA          76.040000
Marin County, CA               83.388235
Napa County, CA                81.333333
Pointe Coupee Parish, LA       76.933333
San Francisco County, CA       81.786364
San Mateo County, CA           82.739474
Santa Clara County, CA         82.653125
Solano County, CA              78.801124
Sonoma County, CA              80.590526
St. Helena Parish, LA          74.750000
Washington County, PA          76.985965
West Baton Rouge Parish, LA    76.620000
West Feliciana Parish, LA      77.150000
Westmoreland County, PA        77.955102
Name: Life Expectancy, dtype: float64

In [14]:
Income_County_df = Income_df.groupby(["State / County Name"])
Income_County_df.head()

,Year,State / County Name,Median Household Income in Dollars,All Ages in Poverty Percent,Median Household Income,County
0,2015,Allegheny County (PA),"$54,412",12.2,54412,Allegheny County (PA)
1,2014,Allegheny County (PA),"$52,385",13.1,52385,Allegheny County (PA)
2,2013,Allegheny County (PA),"$51,400",13.5,51400,Allegheny County (PA)
3,2012,Allegheny County (PA),"$50,831",12.7,50831,Allegheny County (PA)
4,2011,Allegheny County (PA),"$49,682",13.4,49682,Allegheny County (PA)
...,...,...,...,...,...,...
132,2015,Sonoma County (CA),"$66,463",11.0,66463,Sonoma County (CA)
133,2014,Sonoma County (CA),"$66,949",11.3,66949,Sonoma County (CA)
134,2013,Sonoma County (CA),"$61,020",12.4,61020,Sonoma County (CA)
135,2012,Sonoma County (CA),"$59,855",12.1,59855,Sonoma County (CA)
136,2011,Sonoma County (CA),"$60,792",12.2,60792,Sonoma County (CA)

In [22]:
Final_Poverty = Income_County_df["All Ages in Poverty Percent"].mean()
Final_Poverty

State / County Name
Alameda County (CA)             12.800000
Allegheny County (PA)           12.800000
Ascension Parish (LA)           11.983333
Beaver County (PA)              12.583333
Butler County (PA)               9.266667
Contra Costa County (CA)        10.633333
East Baton Rouge Parish (LA)    19.283333
East Feliciana Parish (LA)      20.483333
Iberville Parish (LA)           22.483333
Livingston Parish (LA)          13.500000
Marin County (CA)                8.683333
Napa County (CA)                10.200000
Pointe Coupee Parish (LA)       19.683333
San Francisco County (CA)       13.300000
San Mateo County (CA)            7.866667
Santa Clara County (CA)          9.900000
Solano County (CA)              12.866667
Sonoma County (CA)              11.966667
St. Helena Parish (LA)          23.716667
Washington County (PA)          10.616667
West Baton Rouge Parish (LA)    16.633333
West Feliciana Parish (LA)      23.700000
Westmoreland County (PA)        10.666667
Name: All Ages in Poverty Percent, dtype: float64

In [24]:
Final_Income = Income_County_df["Median Household Income"].mean()
Final_Income

State / County Name
Alameda County (CA)             72504.500000
Allegheny County (PA)           51033.333333
Ascension Parish (LA)           67183.166667
Beaver County (PA)              48246.666667
Butler County (PA)              58961.666667
Contra Costa County (CA)        77401.666667
East Baton Rouge Parish (LA)    47202.333333
East Feliciana Parish (LA)      41621.666667
Iberville Parish (LA)           41200.500000
Livingston Parish (LA)          55066.666667
Marin County (CA)               89711.833333
Napa County (CA)                67022.500000
Pointe Coupee Parish (LA)       42038.666667
San Francisco County (CA)       77263.000000
San Mateo County (CA)           89726.500000
Santa Clara County (CA)         91969.333333
Solano County (CA)              64286.666667
Sonoma County (CA)              62297.000000
St. Helena Parish (LA)          34395.166667
Washington County (PA)          53681.500000
West Baton Rouge Parish (LA)    49285.166667
West Feliciana Parish (LA)      52030.500000
Westmoreland County (PA)        50185.000000
Name: Median Household Income, dtype: float64