In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import matplotlib
matplotlib.style.use('ggplot')

from census import Census

import scipy.stats as st
from scipy.stats import linregress
from scipy.stats import sem

import seaborn as sns

In [4]:
file = '../Resources/life_Expectancy_usa.csv'

In [5]:
life_Expectancy_df = pd.read_csv(file)
life_Expectancy_df.head()

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
0,Alabama,(blank),NaN,75.5,75.2-77.5,0.0328
1,Alabama,"Autauga County, AL",201.0,73.1,56.9-75.1,2.2348
2,Alabama,"Autauga County, AL",202.0,76.9,75.2-77.5,3.3453
3,Alabama,"Autauga County, AL",203.0,NaN,NaN,NaN
4,Alabama,"Autauga County, AL",204.0,75.4,75.2-77.5,1.0216

In [6]:
life_Expectancy_df["State"].value_counts()

California              8059
Texas                   5266
New York                4922
Florida                 4246
Pennsylvania            3219
Illinois                3124
Ohio                    2953
Michigan                2814
North Carolina          2196
New Jersey              2011
Georgia                 1970
Virginia                1908
Arizona                 1527
Indiana                 1512
Tennessee               1498
Massachusetts           1480
Washington              1460
Wisconsin               1412
Maryland                1407
Missouri                1394
Minnesota               1339
Colorado                1250
Alabama                 1182
Louisiana               1149
Kentucky                1116
South Carolina          1104
Oklahoma                1047
Oregon                   837
Connecticut              834
Iowa                     826
Kansas                   771
Nevada                   688
Arkansas                 687
Mississippi              665
Utah                     589
Nebraska                 533
New Mexico               500
West Virginia            485
Maine                    359
Hawaii                   352
Idaho                    299
New Hampshire            296
Montana                  272
Rhode Island             245
South Dakota             226
Delaware                 219
North Dakota             206
Vermont                  185
District of Columbia     180
Alaska                   169
Wyoming                  133
Name: State, dtype: int64

In [7]:
CA_life_Expectancy_df = life_Expectancy_df.loc[(life_Expectancy_df["State"]=="California")]
CA_life_Expectancy_df.head(50)

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
3565,California,(blank),NaN,81.3,79.6-81.6,0.0125
3566,California,"Alameda County, CA",4001.00,87.2,81.7-97.5,2.5534
3567,California,"Alameda County, CA",4002.00,81.5,79.6-81.6,1.0952
3568,California,"Alameda County, CA",4003.00,87.2,81.7-97.5,3.5274
3569,California,"Alameda County, CA",4004.00,82.9,81.7-97.5,1.8118
3570,California,"Alameda County, CA",4005.00,78.8,77.6-79.5,2.1647
3571,California,"Alameda County, CA",4006.00,78.6,77.6-79.5,2.4001
3572,California,"Alameda County, CA",4007.00,80.1,79.6-81.6,2.0179
3573,California,"Alameda County, CA",4008.00,76.9,75.2-77.5,1.5889
3574,California,"Alameda County, CA",4009.00,74.5,56.9-75.1,2.2100
3575,California,"Alameda County, CA",4010.00,77.5,75.2-77.5,1.8596
3576,California,"Alameda County, CA",4011.00,80.3,79.6-81.6,3.0636
3577,California,"Alameda County, CA",4012.00,80.0,79.6-81.6,2.6913
3578,California,"Alameda County, CA",4013.00,75.8,75.2-77.5,1.7997
3579,California,"Alameda County, CA",4014.00,73.5,56.9-75.1,2.1014
3580,California,"Alameda County, CA",4015.00,77.3,75.2-77.5,2.8661
3581,California,"Alameda County, CA",4016.00,77.6,77.6-79.5,3.5769
3582,California,"Alameda County, CA",4017.00,NaN,NaN,NaN
3583,California,"Alameda County, CA",4018.00,77.6,77.6-79.5,2.0340
3584,California,"Alameda County, CA",4022.00,76.6,75.2-77.5,2.6682
3585,California,"Alameda County, CA",4024.00,78.1,77.6-79.5,3.2351
3586,California,"Alameda County, CA",4025.00,NaN,NaN,NaN
3587,California,"Alameda County, CA",4026.00,75.4,75.2-77.5,1.0475
3588,California,"Alameda County, CA",4027.00,77.5,75.2-77.5,2.0026
3589,California,"Alameda County, CA",4028.00,76.0,75.2-77.5,2.7737
3590,California,"Alameda County, CA",4029.00,79.6,79.6-81.6,3.0459
3591,California,"Alameda County, CA",4030.00,81.1,79.6-81.6,1.8675
3592,California,"Alameda County, CA",4031.00,80.0,79.6-81.6,1.5548
3593,California,"Alameda County, CA",4033.00,84.5,81.7-97.5,3.5298
3594,California,"Alameda County, CA",4034.00,81.9,81.7-97.5,1.6965
3595,California,"Alameda County, CA",4035.01,80.0,79.6-81.6,2.7671
3596,California,"Alameda County, CA",4035.02,79.4,77.6-79.5,3.2905
3597,California,"Alameda County, CA",4036.00,80.7,79.6-81.6,2.5415
3598,California,"Alameda County, CA",4037.01,84.4,81.7-97.5,2.0964
3599,California,"Alameda County, CA",4037.02,NaN,NaN,NaN
3600,California,"Alameda County, CA",4038.00,83.8,81.7-97.5,2.5121
3601,California,"Alameda County, CA",4039.00,86.9,81.7-97.5,3.2987
3602,California,"Alameda County, CA",4040.00,82.5,81.7-97.5,3.0159
3603,California,"Alameda County, CA",4041.01,82.7,81.7-97.5,1.7317
3604,California,"Alameda County, CA",4041.02,79.7,79.6-81.6,2.2063
3605,California,"Alameda County, CA",4042.00,84.2,81.7-97.5,1.8697
3606,California,"Alameda County, CA",4043.00,83.3,81.7-97.5,1.6555
3607,California,"Alameda County, CA",4044.00,83.5,81.7-97.5,1.7128
3608,California,"Alameda County, CA",4045.01,86.1,81.7-97.5,2.1925
3609,California,"Alameda County, CA",4045.02,82.4,81.7-97.5,1.3703
3610,California,"Alameda County, CA",4046.00,84.0,81.7-97.5,1.6452
3611,California,"Alameda County, CA",4047.00,82.5,81.7-97.5,1.6124
3612,California,"Alameda County, CA",4048.00,85.2,81.7-97.5,2.6753
3613,California,"Alameda County, CA",4049.00,85.8,81.7-97.5,2.9865
3614,California,"Alameda County, CA",4050.00,81.3,79.6-81.6,1.1745

In [8]:
CA_life_Expectancy_df["County"].value_counts(ascending=True)

San Diego County             1
Mendocino County             1
Contra Costa County          1
San Francisco County         1
Del Norte County             1
                          ...
Santa Clara County, CA     372
Riverside County, CA       453
Orange County, CA          582
San Diego County, CA       627
Los Angeles County, CA    2344
Name: County, Length: 78, dtype: int64

In [9]:
CA_life_Expectancy_df = CA_life_Expectancy_df.drop_duplicates()
CA_life_Expectancy_df

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
3565,California,(blank),NaN,81.3,79.6-81.6,0.0125
3566,California,"Alameda County, CA",4001.00,87.2,81.7-97.5,2.5534
3567,California,"Alameda County, CA",4002.00,81.5,79.6-81.6,1.0952
3568,California,"Alameda County, CA",4003.00,87.2,81.7-97.5,3.5274
3569,California,"Alameda County, CA",4004.00,82.9,81.7-97.5,1.8118
...,...,...,...,...,...,...
11619,California,"Yuba County, CA",408.00,76.9,75.2-77.5,1.2606
11620,California,"Yuba County, CA",409.01,77.6,77.6-79.5,1.1116
11621,California,"Yuba County, CA",409.02,NaN,NaN,NaN
11622,California,"Yuba County, CA",410.00,78.1,77.6-79.5,1.2298
11623,California,"Yuba County, CA",411.00,77.6,77.6-79.5,1.3682

In [10]:
SF_CA_df = CA_life_Expectancy_df.loc[(CA_life_Expectancy_df["County"]=="Alameda County, CA") | (CA_life_Expectancy_df["County"]=="Contra Costa County, CA") | (CA_life_Expectancy_df["County"]=="Marin County, CA") | (CA_life_Expectancy_df["County"]=="Napa County, CA") | (CA_life_Expectancy_df["County"]=="San Francisco County, CA") | (CA_life_Expectancy_df["County"]=="San Mateo County, CA") | (CA_life_Expectancy_df["County"]=="Santa Clara County, CA") | (CA_life_Expectancy_df["County"]=="Solano County, CA") | (CA_life_Expectancy_df["County"]=="Sonoma County, CA")]
SF_CA_df

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
3566,California,"Alameda County, CA",4001.00,87.2,81.7-97.5,2.5534
3567,California,"Alameda County, CA",4002.00,81.5,79.6-81.6,1.0952
3568,California,"Alameda County, CA",4003.00,87.2,81.7-97.5,3.5274
3569,California,"Alameda County, CA",4004.00,82.9,81.7-97.5,1.8118
3570,California,"Alameda County, CA",4005.00,78.8,77.6-79.5,2.1647
...,...,...,...,...,...,...
11169,California,"Sonoma County, CA",1542.01,75.9,75.2-77.5,2.1191
11170,California,"Sonoma County, CA",1542.02,81.4,79.6-81.6,1.5589
11171,California,"Sonoma County, CA",1543.02,82.6,81.7-97.5,1.9657
11172,California,"Sonoma County, CA",1543.03,81.8,81.7-97.5,1.2542
11173,California,"Sonoma County, CA",1543.04,79.9,79.6-81.6,2.0648

In [11]:

SF_life_Ex_df = SF_CA_df.loc[:, ["State", "County", "Life Expectancy"]]
SF_life_Ex_df.head()

           State              County  Life Expectancy
3566  California  Alameda County, CA             87.2
3567  California  Alameda County, CA             81.5
3568  California  Alameda County, CA             87.2
3569  California  Alameda County, CA             82.9
3570  California  Alameda County, CA             78.8

In [12]:
Clean_SF_life_Ex_df = SF_life_Ex_df.dropna(how="any")
Clean_SF_life_Ex_df

            State              County  Life Expectancy
3566   California  Alameda County, CA             87.2
3567   California  Alameda County, CA             81.5
3568   California  Alameda County, CA             87.2
3569   California  Alameda County, CA             82.9
3570   California  Alameda County, CA             78.8
...           ...                 ...              ...
11169  California   Sonoma County, CA             75.9
11170  California   Sonoma County, CA             81.4
11171  California   Sonoma County, CA             82.6
11172  California   Sonoma County, CA             81.8
11173  California   Sonoma County, CA             79.9

[1484 rows x 3 columns]

In [13]:
# not necessary
Clean_SF_life_Ex_df.describe()

       Life Expectancy
count      1484.000000
mean         81.535984
std           3.312786
min          64.400000
25%          79.600000
50%          81.500000
75%          83.600000
max          92.600000

In [14]:

SF_County_df = Clean_SF_life_Ex_df.groupby(["County"])
SF_County_df.head()

            State                    County  Life Expectancy
3566   California        Alameda County, CA             87.2
3567   California        Alameda County, CA             81.5
3568   California        Alameda County, CA             87.2
3569   California        Alameda County, CA             82.9
3570   California        Alameda County, CA             78.8
4003   California   Contra Costa County, CA             78.3
4004   California   Contra Costa County, CA             77.9
4005   California   Contra Costa County, CA             78.8
4006   California   Contra Costa County, CA             75.6
4007   California   Contra Costa County, CA             84.4
7107   California          Marin County, CA             81.1
7108   California          Marin County, CA             81.9
7109   California          Marin County, CA             81.4
7110   California          Marin County, CA             85.8
7111   California          Marin County, CA             81.5
7340   California           Napa County, CA             83.9
7341   California           Napa County, CA             79.2
7342   California           Napa County, CA             78.5
7343   California           Napa County, CA             79.9
7344   California           Napa County, CA             82.1
9853   California  San Francisco County, CA             82.7
9854   California  San Francisco County, CA             85.9
9855   California  San Francisco County, CA             88.5
9856   California  San Francisco County, CA             84.6
9857   California  San Francisco County, CA             89.4
10243  California      San Mateo County, CA             84.1
10244  California      San Mateo County, CA             85.6
10245  California      San Mateo County, CA             81.6
10246  California      San Mateo County, CA             85.5
10247  California      San Mateo County, CA             85.1
10491  California    Santa Clara County, CA             84.4
10492  California    Santa Clara County, CA             79.9
10493  California    Santa Clara County, CA             77.4
10494  California    Santa Clara County, CA             80.2
10495  California    Santa Clara County, CA             81.0
10979  California         Solano County, CA             80.1
10980  California         Solano County, CA             79.7
10981  California         Solano County, CA             83.5
10982  California         Solano County, CA             85.0
10983  California         Solano County, CA             76.7
11075  California         Sonoma County, CA             83.8
11076  California         Sonoma County, CA             80.9
11077  California         Sonoma County, CA             77.1
11078  California         Sonoma County, CA             80.2
11079  California         Sonoma County, CA             82.3

In [15]:
# SanFrancisco  county info summary 
SF_County_df.describe()

                         Life Expectancy                                    \
                                   count       mean       std   min    25%
County
Alameda County, CA                 338.0  80.845858  3.347642  71.7  78.70
Contra Costa County, CA            195.0  80.813333  3.583327  71.6  78.20
Marin County, CA                    51.0  83.388235  2.988086  76.2  81.45
Napa County, CA                     36.0  81.333333  2.313439  74.5  79.85
San Francisco County, CA           176.0  81.786364  3.960020  64.4  79.70
San Mateo County, CA               152.0  82.739474  2.615217  76.2  81.20
Santa Clara County, CA             352.0  82.653125  2.520772  75.9  81.00
Solano County, CA                   89.0  78.801124  3.066887  70.1  76.70
Sonoma County, CA                   95.0  80.590526  2.686415  73.2  78.80


                            50%     75%   max
County
Alameda County, CA        81.00  82.800  92.6
Contra Costa County, CA   80.90  83.500  90.0
Marin County, CA          82.90  85.550  91.2
Napa County, CA           82.10  82.925  84.6
San Francisco County, CA  82.15  84.250  89.4
San Mateo County, CA      82.55  84.700  91.3
Santa Clara County, CA    82.35  84.400  91.6
Solano County, CA         79.10  80.700  85.0
Sonoma County, CA         80.50  82.400  86.8

In [18]:
Life_Expectancy_mean_df = SF_County_df["Life Expectancy"].mean()
Life_Expectancy_mean_df

County
Alameda County, CA          80.845858
Contra Costa County, CA     80.813333
Marin County, CA            83.388235
Napa County, CA             81.333333
San Francisco County, CA    81.786364
San Mateo County, CA        82.739474
Santa Clara County, CA      82.653125
Solano County, CA           78.801124
Sonoma County, CA           80.590526
Name: Life Expectancy, dtype: float64

In [19]:
#https://www.macrotrends.net/countries/USA/united-states/life-expectancy
#Average Life expectancy in US during 2010 to 2015 was (78.74 + 78.64 + 78.79 + 78.91 + 78.89) / 5

# Louisiana Data Analysis

In [20]:

life_Expectancy_df.head()

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
0,Alabama,(blank),NaN,75.5,75.2-77.5,0.0328
1,Alabama,"Autauga County, AL",201.0,73.1,56.9-75.1,2.2348
2,Alabama,"Autauga County, AL",202.0,76.9,75.2-77.5,3.3453
3,Alabama,"Autauga County, AL",203.0,NaN,NaN,NaN
4,Alabama,"Autauga County, AL",204.0,75.4,75.2-77.5,1.0216

In [21]:
LA_life_Expectancy_df = life_Expectancy_df.loc[(life_Expectancy_df["State"]=="Louisiana")]
LA_life_Expectancy_df.head()

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
28323,Louisiana,(blank),NaN,76.0,75.2-77.5,0.0343
28324,Louisiana,"Acadia Parish, LA",9601.0,71.5,56.9-75.1,1.2890
28325,Louisiana,"Acadia Parish, LA",9602.0,74.7,56.9-75.1,1.3573
28326,Louisiana,"Acadia Parish, LA",9603.0,75.1,56.9-75.1,1.0201
28327,Louisiana,"Acadia Parish, LA",9604.0,76.6,75.2-77.5,1.3168

In [22]:
LA_life_Expectancy_df["County"].value_counts()

Orleans Parish, LA             176
Jefferson Parish, LA           125
East Baton Rouge Parish, LA     92
Caddo Parish, LA                64
Calcasieu Parish, LA            44
                              ...
Cameron Parish                   1
Terrebonne Parish                1
Lafourche Parish                 1
Iberia Parish                    1
St. Mary Parish                  1
Name: County, Length: 76, dtype: int64

In [23]:
BR_LA_df = LA_life_Expectancy_df.loc[(LA_life_Expectancy_df["County"]=="Ascension Parish, LA") | (LA_life_Expectancy_df["County"]=="East Baton Rouge Parish, LA") | (LA_life_Expectancy_df["County"]=="East Feliciana Parish, LA") | (LA_life_Expectancy_df["County"]=="Iberville Parish, LA") | (LA_life_Expectancy_df["County"]=="Livingston Parish, LA") | (LA_life_Expectancy_df["County"]=="Pointe Coupee Parish, LA") | (LA_life_Expectancy_df["County"]=="St. Helena Parish, LA") | (LA_life_Expectancy_df["County"]=="West Baton Rouge Parish, LA") | (LA_life_Expectancy_df["County"]=="West Feliciana Parish, LA")]

In [24]:
BR_LA_df.head(10)

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
28341,Louisiana,"Ascension Parish, LA",301.01,80.4,79.6-81.6,3.4652
28342,Louisiana,"Ascension Parish, LA",301.02,80.1,79.6-81.6,2.3893
28343,Louisiana,"Ascension Parish, LA",301.03,84.7,81.7-97.5,3.4597
28344,Louisiana,"Ascension Parish, LA",302.03,NaN,NaN,NaN
28345,Louisiana,"Ascension Parish, LA",302.04,78.9,77.6-79.5,1.0174
28346,Louisiana,"Ascension Parish, LA",302.05,80.6,79.6-81.6,3.6629
28347,Louisiana,"Ascension Parish, LA",302.06,77.8,77.6-79.5,1.5141
28348,Louisiana,"Ascension Parish, LA",303.00,76.2,75.2-77.5,0.9352
28349,Louisiana,"Ascension Parish, LA",304.01,76.8,75.2-77.5,1.6267
28350,Louisiana,"Ascension Parish, LA",304.02,75.1,56.9-75.1,1.0754

In [25]:
BR_LA_df["County"].value_counts()

East Baton Rouge Parish, LA    92
Livingston Parish, LA          17
Ascension Parish, LA           14
Iberville Parish, LA            7
Pointe Coupee Parish, LA        6
East Feliciana Parish, LA       5
West Baton Rouge Parish, LA     5
West Feliciana Parish, LA       3
St. Helena Parish, LA           2
Name: County, dtype: int64

In [26]:
LA_life_Expectancy_df = LA_life_Expectancy_df.drop_duplicates()
LA_life_Expectancy_df

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
28323,Louisiana,(blank),NaN,76.0,75.2-77.5,0.0343
28324,Louisiana,"Acadia Parish, LA",9601.0,71.5,56.9-75.1,1.2890
28325,Louisiana,"Acadia Parish, LA",9602.0,74.7,56.9-75.1,1.3573
28326,Louisiana,"Acadia Parish, LA",9603.0,75.1,56.9-75.1,1.0201
28327,Louisiana,"Acadia Parish, LA",9604.0,76.6,75.2-77.5,1.3168
...,...,...,...,...,...,...
29467,Louisiana,"West Feliciana Parish, LA",9518.0,80.8,79.6-81.6,2.0021
29468,Louisiana,"Winn Parish, LA",9601.0,77.0,75.2-77.5,1.5687
29469,Louisiana,"Winn Parish, LA",9602.0,77.1,75.2-77.5,1.5037
29470,Louisiana,"Winn Parish, LA",9603.0,71.4,56.9-75.1,1.5021
29471,Louisiana,"Winn Parish, LA",9604.0,70.3,56.9-75.1,1.6468

In [27]:
LA_life_Ex_df = BR_LA_df.loc[:, ["State", "County", "Life Expectancy"]]
LA_life_Ex_df.head()

           State                County  Life Expectancy
28341  Louisiana  Ascension Parish, LA             80.4
28342  Louisiana  Ascension Parish, LA             80.1
28343  Louisiana  Ascension Parish, LA             84.7
28344  Louisiana  Ascension Parish, LA              NaN
28345  Louisiana  Ascension Parish, LA             78.9

In [28]:
Clean_LA_life_Ex_df = LA_life_Ex_df.dropna(how="any")
Clean_LA_life_Ex_df

           State                       County  Life Expectancy
28341  Louisiana         Ascension Parish, LA             80.4
28342  Louisiana         Ascension Parish, LA             80.1
28343  Louisiana         Ascension Parish, LA             84.7
28345  Louisiana         Ascension Parish, LA             78.9
28346  Louisiana         Ascension Parish, LA             80.6
...          ...                          ...              ...
29459  Louisiana  West Baton Rouge Parish, LA             76.0
29460  Louisiana  West Baton Rouge Parish, LA             79.3
29461  Louisiana  West Baton Rouge Parish, LA             78.6
29465  Louisiana    West Feliciana Parish, LA             73.5
29467  Louisiana    West Feliciana Parish, LA             80.8

[136 rows x 3 columns]

In [29]:
LA_life_Ex_df.describe()

       Life Expectancy
count       136.000000
mean         75.578676
std           4.090738
min          66.000000
25%          72.700000
50%          75.950000
75%          78.500000
max          85.700000

In [30]:
BR_County_df = Clean_LA_life_Ex_df.groupby(["County"])
BR_County_df.head()

           State                       County  Life Expectancy
28341  Louisiana         Ascension Parish, LA             80.4
28342  Louisiana         Ascension Parish, LA             80.1
28343  Louisiana         Ascension Parish, LA             84.7
28345  Louisiana         Ascension Parish, LA             78.9
28346  Louisiana         Ascension Parish, LA             80.6
28538  Louisiana  East Baton Rouge Parish, LA             67.9
28539  Louisiana  East Baton Rouge Parish, LA             69.1
28540  Louisiana  East Baton Rouge Parish, LA             66.1
28541  Louisiana  East Baton Rouge Parish, LA             72.6
28542  Louisiana  East Baton Rouge Parish, LA             66.1
28633  Louisiana    East Feliciana Parish, LA             80.2
28634  Louisiana    East Feliciana Parish, LA             74.0
28635  Louisiana    East Feliciana Parish, LA             76.2
28636  Louisiana    East Feliciana Parish, LA             76.3
28637  Louisiana    East Feliciana Parish, LA             73.3
28673  Louisiana         Iberville Parish, LA             75.7
28674  Louisiana         Iberville Parish, LA             77.7
28675  Louisiana         Iberville Parish, LA             74.3
28676  Louisiana         Iberville Parish, LA             70.2
28677  Louisiana         Iberville Parish, LA             70.7
28899  Louisiana        Livingston Parish, LA             76.2
28900  Louisiana        Livingston Parish, LA             75.1
28901  Louisiana        Livingston Parish, LA             77.5
28902  Louisiana        Livingston Parish, LA             78.0
28904  Louisiana        Livingston Parish, LA             78.0
29164  Louisiana     Pointe Coupee Parish, LA             75.2
29165  Louisiana     Pointe Coupee Parish, LA             81.1
29166  Louisiana     Pointe Coupee Parish, LA             78.3
29167  Louisiana     Pointe Coupee Parish, LA             76.0
29168  Louisiana     Pointe Coupee Parish, LA             71.0
29249  Louisiana        St. Helena Parish, LA             77.3
29250  Louisiana        St. Helena Parish, LA             72.2
29457  Louisiana  West Baton Rouge Parish, LA             74.8
29458  Louisiana  West Baton Rouge Parish, LA             74.4
29459  Louisiana  West Baton Rouge Parish, LA             76.0
29460  Louisiana  West Baton Rouge Parish, LA             79.3
29461  Louisiana  West Baton Rouge Parish, LA             78.6
29465  Louisiana    West Feliciana Parish, LA             73.5
29467  Louisiana    West Feliciana Parish, LA             80.8

In [31]:
# SanFrancisco  county info summary 
BR_County_df.describe()

                            Life Expectancy                             \
                                      count       mean       std   min
County
Ascension Parish, LA                   13.0  78.400000  2.896262  74.2
East Baton Rouge Parish, LA            81.0  74.965432  4.640182  66.0
East Feliciana Parish, LA               5.0  76.000000  2.695366  73.3
Iberville Parish, LA                    7.0  74.028571  2.946588  70.2
Livingston Parish, LA                  15.0  76.040000  1.892013  73.0
Pointe Coupee Parish, LA                6.0  76.933333  3.680036  71.0
St. Helena Parish, LA                   2.0  74.750000  3.606245  72.2
West Baton Rouge Parish, LA             5.0  76.620000  2.220811  74.4
West Feliciana Parish, LA               2.0  77.150000  5.161880  73.5


                                25%    50%     75%   max
County
Ascension Parish, LA         76.200  78.70  80.300  84.7
East Baton Rouge Parish, LA  71.300  75.20  78.500  85.7
East Feliciana Parish, LA    74.000  76.20  76.300  80.2
Iberville Parish, LA         71.700  74.30  76.300  77.7
Livingston Parish, LA        74.950  76.20  77.350  79.4
Pointe Coupee Parish, LA     75.400  77.15  79.575  81.1
St. Helena Parish, LA        73.475  74.75  76.025  77.3
West Baton Rouge Parish, LA  74.800  76.00  78.600  79.3
West Feliciana Parish, LA    75.325  77.15  78.975  80.8

In [32]:
#additional
BR_County_df["Life Expectancy"].value_counts()

County                       Life Expectancy
Ascension Parish, LA         74.2               1
                             75.1               1
                             75.4               1
                             76.2               1
                             76.8               1
                                               ..
West Baton Rouge Parish, LA  76.0               1
                             78.6               1
                             79.3               1
West Feliciana Parish, LA    73.5               1
                             80.8               1
Name: Life Expectancy, Length: 114, dtype: int64

In [33]:
BR_Life_Expectancy_mean_df = BR_County_df["Life Expectancy"].mean()
BR_Life_Expectancy_mean_df

County
Ascension Parish, LA           78.400000
East Baton Rouge Parish, LA    74.965432
East Feliciana Parish, LA      76.000000
Iberville Parish, LA           74.028571
Livingston Parish, LA          76.040000
Pointe Coupee Parish, LA       76.933333
St. Helena Parish, LA          74.750000
West Baton Rouge Parish, LA    76.620000
West Feliciana Parish, LA      77.150000
Name: Life Expectancy, dtype: float64

In [34]:
BR_County_df = Clean_LA_life_Ex_df.groupby(["County"])
BR_County_df.head()

           State                       County  Life Expectancy
28341  Louisiana         Ascension Parish, LA             80.4
28342  Louisiana         Ascension Parish, LA             80.1
28343  Louisiana         Ascension Parish, LA             84.7
28345  Louisiana         Ascension Parish, LA             78.9
28346  Louisiana         Ascension Parish, LA             80.6
28538  Louisiana  East Baton Rouge Parish, LA             67.9
28539  Louisiana  East Baton Rouge Parish, LA             69.1
28540  Louisiana  East Baton Rouge Parish, LA             66.1
28541  Louisiana  East Baton Rouge Parish, LA             72.6
28542  Louisiana  East Baton Rouge Parish, LA             66.1
28633  Louisiana    East Feliciana Parish, LA             80.2
28634  Louisiana    East Feliciana Parish, LA             74.0
28635  Louisiana    East Feliciana Parish, LA             76.2
28636  Louisiana    East Feliciana Parish, LA             76.3
28637  Louisiana    East Feliciana Parish, LA             73.3
28673  Louisiana         Iberville Parish, LA             75.7
28674  Louisiana         Iberville Parish, LA             77.7
28675  Louisiana         Iberville Parish, LA             74.3
28676  Louisiana         Iberville Parish, LA             70.2
28677  Louisiana         Iberville Parish, LA             70.7
28899  Louisiana        Livingston Parish, LA             76.2
28900  Louisiana        Livingston Parish, LA             75.1
28901  Louisiana        Livingston Parish, LA             77.5
28902  Louisiana        Livingston Parish, LA             78.0
28904  Louisiana        Livingston Parish, LA             78.0
29164  Louisiana     Pointe Coupee Parish, LA             75.2
29165  Louisiana     Pointe Coupee Parish, LA             81.1
29166  Louisiana     Pointe Coupee Parish, LA             78.3
29167  Louisiana     Pointe Coupee Parish, LA             76.0
29168  Louisiana     Pointe Coupee Parish, LA             71.0
29249  Louisiana        St. Helena Parish, LA             77.3
29250  Louisiana        St. Helena Parish, LA             72.2
29457  Louisiana  West Baton Rouge Parish, LA             74.8
29458  Louisiana  West Baton Rouge Parish, LA             74.4
29459  Louisiana  West Baton Rouge Parish, LA             76.0
29460  Louisiana  West Baton Rouge Parish, LA             79.3
29461  Louisiana  West Baton Rouge Parish, LA             78.6
29465  Louisiana    West Feliciana Parish, LA             73.5
29467  Louisiana    West Feliciana Parish, LA             80.8

# Pittsburgh, PA Data Analysis

In [35]:
PA_life_Expectancy_df = life_Expectancy_df.loc[(life_Expectancy_df["State"]=="Pennsylvania")]
PA_life_Expectancy_df.head(50)

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
55428,Pennsylvania,(blank),NaN,78.6,77.6-79.5,0.0196
55429,Pennsylvania,"Adams County, PA",301.01,80.3,79.6-81.6,1.3822
55430,Pennsylvania,"Adams County, PA",301.02,81.6,79.6-81.6,2.8520
55431,Pennsylvania,"Adams County, PA",302.00,78.4,77.6-79.5,1.1067
55432,Pennsylvania,"Adams County, PA",303.00,81.5,79.6-81.6,2.1068
55433,Pennsylvania,"Adams County, PA",304.00,78.2,77.6-79.5,0.9213
55434,Pennsylvania,"Adams County, PA",305.00,79.1,77.6-79.5,1.2849
55435,Pennsylvania,"Adams County, PA",306.00,78.4,77.6-79.5,1.0090
55436,Pennsylvania,"Adams County, PA",307.00,79.1,77.6-79.5,1.1346
55437,Pennsylvania,"Adams County, PA",308.00,80.2,79.6-81.6,0.9498
55438,Pennsylvania,"Adams County, PA",309.00,78.2,77.6-79.5,0.9153
55439,Pennsylvania,"Adams County, PA",310.00,81.1,79.6-81.6,2.3474
55440,Pennsylvania,"Adams County, PA",311.01,78.2,77.6-79.5,1.4791
55441,Pennsylvania,"Adams County, PA",311.02,85.5,81.7-97.5,3.6576
55442,Pennsylvania,"Adams County, PA",312.01,81.7,81.7-97.5,1.9519
55443,Pennsylvania,"Adams County, PA",312.02,80.2,79.6-81.6,1.4696
55444,Pennsylvania,"Adams County, PA",312.03,80.2,79.6-81.6,1.4351
55445,Pennsylvania,"Adams County, PA",313.00,77.2,75.2-77.5,1.5881
55446,Pennsylvania,"Adams County, PA",314.01,77.8,77.6-79.5,1.0484
55447,Pennsylvania,"Adams County, PA",314.02,81.3,79.6-81.6,1.7904
55448,Pennsylvania,"Adams County, PA",315.01,NaN,NaN,NaN
55449,Pennsylvania,"Adams County, PA",315.02,80.5,79.6-81.6,1.9678
55450,Pennsylvania,"Adams County, PA",316.00,82.2,81.7-97.5,1.2443
55451,Pennsylvania,"Adams County, PA",317.00,79.0,77.6-79.5,2.3067
55452,Pennsylvania,"Allegheny County, PA",103.00,NaN,NaN,NaN
55453,Pennsylvania,"Allegheny County, PA",201.00,NaN,NaN,NaN
55454,Pennsylvania,"Allegheny County, PA",203.00,NaN,NaN,NaN
55455,Pennsylvania,"Allegheny County, PA",305.00,69.6,56.9-75.1,2.2644
55456,Pennsylvania,"Allegheny County, PA",402.00,72.9,56.9-75.1,2.2848
55457,Pennsylvania,"Allegheny County, PA",404.00,NaN,NaN,NaN
55458,Pennsylvania,"Allegheny County, PA",405.00,NaN,NaN,NaN
55459,Pennsylvania,"Allegheny County, PA",406.00,NaN,NaN,NaN
55460,Pennsylvania,"Allegheny County, PA",409.00,NaN,NaN,NaN
55461,Pennsylvania,"Allegheny County, PA",501.00,67.6,56.9-75.1,2.1837
55462,Pennsylvania,"Allegheny County, PA",506.00,72.3,56.9-75.1,2.6052
55463,Pennsylvania,"Allegheny County, PA",509.00,67.0,56.9-75.1,2.1150
55464,Pennsylvania,"Allegheny County, PA",510.00,NaN,NaN,NaN
55465,Pennsylvania,"Allegheny County, PA",511.00,NaN,NaN,NaN
55466,Pennsylvania,"Allegheny County, PA",603.00,77.0,75.2-77.5,1.2291
55467,Pennsylvania,"Allegheny County, PA",605.00,74.7,56.9-75.1,2.9542
55468,Pennsylvania,"Allegheny County, PA",703.00,81.3,79.6-81.6,1.6530
55469,Pennsylvania,"Allegheny County, PA",705.00,NaN,NaN,NaN
55470,Pennsylvania,"Allegheny County, PA",706.00,81.3,79.6-81.6,2.1116
55471,Pennsylvania,"Allegheny County, PA",708.00,81.3,79.6-81.6,3.2704
55472,Pennsylvania,"Allegheny County, PA",709.00,79.6,79.6-81.6,1.9608
55473,Pennsylvania,"Allegheny County, PA",802.00,79.4,77.6-79.5,1.0038
55474,Pennsylvania,"Allegheny County, PA",804.00,NaN,NaN,NaN
55475,Pennsylvania,"Allegheny County, PA",806.00,81.3,79.6-81.6,1.6166
55476,Pennsylvania,"Allegheny County, PA",807.00,NaN,NaN,NaN
55477,Pennsylvania,"Allegheny County, PA",809.00,78.5,77.6-79.5,1.1490

In [36]:
PA_life_Expectancy_df["County"].value_counts(ascending=True)

(blank)                      1
Cameron County, PA           2
Sullivan County, PA          2
Fulton County, PA            3
Forest County, PA            3
                          ...
Bucks County, PA           143
Delaware County, PA        144
Montgomery County, PA      211
Philadelphia County, PA    384
Allegheny County, PA       402
Name: County, Length: 68, dtype: int64

In [37]:
PA_life_Expectancy_df = PA_life_Expectancy_df.drop_duplicates()
PA_life_Expectancy_df

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
55428,Pennsylvania,(blank),NaN,78.6,77.6-79.5,0.0196
55429,Pennsylvania,"Adams County, PA",301.01,80.3,79.6-81.6,1.3822
55430,Pennsylvania,"Adams County, PA",301.02,81.6,79.6-81.6,2.8520
55431,Pennsylvania,"Adams County, PA",302.00,78.4,77.6-79.5,1.1067
55432,Pennsylvania,"Adams County, PA",303.00,81.5,79.6-81.6,2.1068
...,...,...,...,...,...,...
58657,Pennsylvania,"York County, PA",238.22,78.8,77.6-79.5,1.0130
58658,Pennsylvania,"York County, PA",239.01,80.0,79.6-81.6,1.3009
58659,Pennsylvania,"York County, PA",239.02,79.0,77.6-79.5,1.4327
58660,Pennsylvania,"York County, PA",240.01,76.2,75.2-77.5,1.6274
58661,Pennsylvania,"York County, PA",240.02,79.6,79.6-81.6,1.2696

In [38]:
PIT_PA_df = PA_life_Expectancy_df.loc[(PA_life_Expectancy_df["County"]=="Allegheny County, PA") | (PA_life_Expectancy_df["County"]=="Beaver County, PA") | (PA_life_Expectancy_df["County"]=="Butler County, PA") | (PA_life_Expectancy_df["County"]=="Washington County, PA") | (PA_life_Expectancy_df["County"]=="Westmoreland County, PA")]
PIT_PA_df

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
55452,Pennsylvania,"Allegheny County, PA",103.00,NaN,NaN,NaN
55453,Pennsylvania,"Allegheny County, PA",201.00,NaN,NaN,NaN
55454,Pennsylvania,"Allegheny County, PA",203.00,NaN,NaN,NaN
55455,Pennsylvania,"Allegheny County, PA",305.00,69.6,56.9-75.1,2.2644
55456,Pennsylvania,"Allegheny County, PA",402.00,72.9,56.9-75.1,2.2848
...,...,...,...,...,...,...
58560,Pennsylvania,"Westmoreland County, PA",8083.00,78.0,77.6-79.5,0.9858
58561,Pennsylvania,"Westmoreland County, PA",8084.01,79.6,79.6-81.6,3.1956
58562,Pennsylvania,"Westmoreland County, PA",8084.02,82.0,81.7-97.5,1.6908
58563,Pennsylvania,"Westmoreland County, PA",8085.00,78.9,77.6-79.5,1.3245
58564,Pennsylvania,"Westmoreland County, PA",8086.00,79.2,77.6-79.5,1.2445

In [39]:
PA_life_Ex_df = PIT_PA_df.loc[:, ["State", "County", "Life Expectancy"]]
PA_life_Ex_df.head()

              State                County  Life Expectancy
55452  Pennsylvania  Allegheny County, PA              NaN
55453  Pennsylvania  Allegheny County, PA              NaN
55454  Pennsylvania  Allegheny County, PA              NaN
55455  Pennsylvania  Allegheny County, PA             69.6
55456  Pennsylvania  Allegheny County, PA             72.9

In [40]:
Clean_PA_life_Ex_df = PA_life_Ex_df.dropna(how="any")
Clean_PA_life_Ex_df

              State                   County  Life Expectancy
55455  Pennsylvania     Allegheny County, PA             69.6
55456  Pennsylvania     Allegheny County, PA             72.9
55461  Pennsylvania     Allegheny County, PA             67.6
55462  Pennsylvania     Allegheny County, PA             72.3
55463  Pennsylvania     Allegheny County, PA             67.0
...             ...                      ...              ...
58560  Pennsylvania  Westmoreland County, PA             78.0
58561  Pennsylvania  Westmoreland County, PA             79.6
58562  Pennsylvania  Westmoreland County, PA             82.0
58563  Pennsylvania  Westmoreland County, PA             78.9
58564  Pennsylvania  Westmoreland County, PA             79.2

[605 rows x 3 columns]

In [41]:
# population statistics for PIT
PIT_population_stat = Clean_PA_life_Ex_df.describe()
PIT_population_stat

       Life Expectancy
count       605.000000
mean         77.442314
std           3.782868
min          62.000000
25%          75.300000
50%          78.000000
75%          80.100000
max          86.000000

In [42]:
PIT_County_df = Clean_PA_life_Ex_df.groupby(["County"])
PIT_County_df.head()

              State                   County  Life Expectancy
55455  Pennsylvania     Allegheny County, PA             69.6
55456  Pennsylvania     Allegheny County, PA             72.9
55461  Pennsylvania     Allegheny County, PA             67.6
55462  Pennsylvania     Allegheny County, PA             72.3
55463  Pennsylvania     Allegheny County, PA             67.0
55873  Pennsylvania        Beaver County, PA             76.7
55874  Pennsylvania        Beaver County, PA             75.6
55875  Pennsylvania        Beaver County, PA             81.7
55876  Pennsylvania        Beaver County, PA             80.6
55877  Pennsylvania        Beaver County, PA             75.8
56216  Pennsylvania        Butler County, PA             79.6
56217  Pennsylvania        Butler County, PA             79.2
56218  Pennsylvania        Butler County, PA             70.6
56219  Pennsylvania        Butler County, PA             66.9
56220  Pennsylvania        Butler County, PA             73.9
58392  Pennsylvania    Washington County, PA             69.0
58393  Pennsylvania    Washington County, PA             80.2
58394  Pennsylvania    Washington County, PA             74.8
58395  Pennsylvania    Washington County, PA             76.7
58396  Pennsylvania    Washington County, PA             74.5
58465  Pennsylvania  Westmoreland County, PA             68.9
58466  Pennsylvania  Westmoreland County, PA             75.9
58467  Pennsylvania  Westmoreland County, PA             75.5
58468  Pennsylvania  Westmoreland County, PA             74.8
58469  Pennsylvania  Westmoreland County, PA             79.0

In [43]:
# Pittsburgh  county info summary 
PIT_County_df.describe()

                        Life Expectancy                                    \
                                  count       mean       std   min    25%
County
Allegheny County, PA              357.0  77.236134  4.059004  62.0  74.60
Beaver County, PA                  50.0  77.204000  3.657922  65.6  75.45
Butler County, PA                  43.0  78.867442  3.168875  66.9  78.05
Washington County, PA              57.0  76.985965  3.227363  69.0  75.00
Westmoreland County, PA            98.0  77.955102  3.169348  68.9  76.15


                          50%     75%   max
County
Allegheny County, PA     77.8  80.300  86.0
Beaver County, PA        77.2  80.125  83.1
Butler County, PA        79.4  80.300  85.0
Washington County, PA    77.4  79.400  82.6
Westmoreland County, PA  78.4  79.600  84.4

In [44]:
PIT_Life_Expectancy_mean_df = PIT_County_df["Life Expectancy"].mean()
PIT_Life_Expectancy_mean_df

County
Allegheny County, PA       77.236134
Beaver County, PA          77.204000
Butler County, PA          78.867442
Washington County, PA      76.985965
Westmoreland County, PA    77.955102
Name: Life Expectancy, dtype: float64

# Comparison of SF , BR and PIT

In [45]:
Clean_All_Cities_Df = pd.concat([Clean_LA_life_Ex_df, Clean_PA_life_Ex_df, Clean_SF_life_Ex_df], axis=0)
Clean_All_Cities_Df

            State                County  Life Expectancy
28341   Louisiana  Ascension Parish, LA             80.4
28342   Louisiana  Ascension Parish, LA             80.1
28343   Louisiana  Ascension Parish, LA             84.7
28345   Louisiana  Ascension Parish, LA             78.9
28346   Louisiana  Ascension Parish, LA             80.6
...           ...                   ...              ...
11169  California     Sonoma County, CA             75.9
11170  California     Sonoma County, CA             81.4
11171  California     Sonoma County, CA             82.6
11172  California     Sonoma County, CA             81.8
11173  California     Sonoma County, CA             79.9

[2225 rows x 3 columns]

In [46]:
PA_PIT_life_Ex_df = PIT_PA_df.loc[:, ["State", "County", "Life Expectancy"]]
PA_PIT_life_Ex_df.head()

              State                County  Life Expectancy
55452  Pennsylvania  Allegheny County, PA              NaN
55453  Pennsylvania  Allegheny County, PA              NaN
55454  Pennsylvania  Allegheny County, PA              NaN
55455  Pennsylvania  Allegheny County, PA             69.6
55456  Pennsylvania  Allegheny County, PA             72.9

In [47]:
CA_SF_life_Ex_df = SF_CA_df.loc[:, ["State", "County", "Life Expectancy"]]
CA_SF_life_Ex_df.head()

           State              County  Life Expectancy
3566  California  Alameda County, CA             87.2
3567  California  Alameda County, CA             81.5
3568  California  Alameda County, CA             87.2
3569  California  Alameda County, CA             82.9
3570  California  Alameda County, CA             78.8

In [48]:
LA_life_Ex_df = BR_LA_df.loc[:, ["State", "County", "Life Expectancy"]]
LA_life_Ex_df.head()

           State                County  Life Expectancy
28341  Louisiana  Ascension Parish, LA             80.4
28342  Louisiana  Ascension Parish, LA             80.1
28343  Louisiana  Ascension Parish, LA             84.7
28344  Louisiana  Ascension Parish, LA              NaN
28345  Louisiana  Ascension Parish, LA             78.9

In [49]:
All_City_County_Df = pd.concat([CA_SF_life_Ex_df, LA_life_Ex_df, PA_PIT_life_Ex_df], axis=0)
All_City_County_Df

              State                   County  Life Expectancy
3566     California       Alameda County, CA             87.2
3567     California       Alameda County, CA             81.5
3568     California       Alameda County, CA             87.2
3569     California       Alameda County, CA             82.9
3570     California       Alameda County, CA             78.8
...             ...                      ...              ...
58560  Pennsylvania  Westmoreland County, PA             78.0
58561  Pennsylvania  Westmoreland County, PA             79.6
58562  Pennsylvania  Westmoreland County, PA             82.0
58563  Pennsylvania  Westmoreland County, PA             78.9
58564  Pennsylvania  Westmoreland County, PA             79.2

[2389 rows x 3 columns]

In [50]:
Clean_All_City_County_df = All_City_County_Df.dropna(how="any")
Clean_All_City_County_df

              State                   County  Life Expectancy
3566     California       Alameda County, CA             87.2
3567     California       Alameda County, CA             81.5
3568     California       Alameda County, CA             87.2
3569     California       Alameda County, CA             82.9
3570     California       Alameda County, CA             78.8
...             ...                      ...              ...
58560  Pennsylvania  Westmoreland County, PA             78.0
58561  Pennsylvania  Westmoreland County, PA             79.6
58562  Pennsylvania  Westmoreland County, PA             82.0
58563  Pennsylvania  Westmoreland County, PA             78.9
58564  Pennsylvania  Westmoreland County, PA             79.2

[2225 rows x 3 columns]

In [51]:
Clean_All_City_County_df.to_csv(r'F:/Final_green_city/green_city/Output/Visu_Life_All_Cities.csv', index = False, header = True)